### ISSUE TITLE
Conference Logger Plugin - bugs and wishes

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#203]
Original [issue 188](https://code.google.com/p/psi-dev/issues/detail?id=188) created by psi-plus on 2009-11-28T00:11:02.000Z:

Багрепорты, предложения, замечания по плагину.
## При багрепортах указывайте полную версию psi+ (+ОС) и версию плагина.

Предложения:
1. Сохранять лог в UTF-8, поскольку не все общаются /только/ на английском 
и русском языках.
2. Добавить сохранение логов приватов в конференциях, ибо psi+ сохраняет 
лишь чат с контактом, написавшим в ростер.
3. Изменить формат имени файла с логом, удобнее же и глазу привычнее:
а) почему бы не сделать логичное ник@домен и конференция@сервер соотв, 
&quot;_in_&quot; тоже заменить на какой-нибудь символ;
б) добавить общее расширение к имени файла, например .log, эти 
вразброс .ru .org .net .jp неудобны.

**Comment by Neustradamus** [comment]
The problem is always here: "?" and no minimize/maximize buttons.
