### ISSUE TITLE
Показ времени собеседника около счётчика символов

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#250]
Original [issue 236](https://code.google.com/p/psi-dev/issues/detail?id=236) created by psi-plus on 2010-01-17T02:21:37.000Z:

<b>Шаги по воспроизведению проблемы:</b>
- Начать чатиться с собеседником
- Вдруг задаться вопросом сколько у него времени

<b>Каков ожидаемый результат?</b>
- Без лишних телодвижений увидеть время собеседника - предлагаю разместить
  симпатишные часики около счётчика символов (указал на скриншоте)

<b>Что вы видите вместо этого?</b>
- Вижу окно чата с локальным временем, времени собеседника нет, приходится
  наводить мышку на контакт в ростере и смотреть время там.

Какую версию Psi+ вы используете? Какую операционную систему?
- Это не имеет значения.

Просьба предоставить любую дополнительную информацию по проблеме ниже.
- Подробности на скриншоте.

**Comment by Vitozz** [comment]
Any news?

**Comment by Ri0n** [comment]
two clicks to see time via vcard dialog. good enough for me.
