### ISSUE TITLE
download langpack on first start. make psi+ langpacks storage

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#337]
Original [issue 325](https://code.google.com/p/psi-dev/issues/detail?id=325) created by psi-plus on 2010-08-03T16:24:27.000Z:

Just one cool feature i noticed in ultraedit =)
just a dropdown list with languages and download bar.

**Comment by Vitozz** [comment]
Look like fixed.

**Comment by tehnick** [comment]
https://github.com/psi-plus/psi-plus-l10n
