### ISSUE TITLE
Client Switcher Plugin -- баги и предложения

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#392]
Original [issue 382](https://code.google.com/p/psi-dev/issues/detail?id=382) created by psi-plus on 2010-12-12T14:30:33.000Z:

Обсуждение плагина для гибкой настройки версии клиента

**Comment by 0ktav1us** [comment]
> Original [issue 382](https://code.google.com/p/psi-dev/issues/detail?id=382) created by psi-plus on 2010-12-12T14:30:33.000Z:
> 
> Обсуждение плагина для гибкой настройки версии клиента

Привет Ri0n!
Не пишет нужную информацию в плагине версии 0.0.18.
Выбираю User Defined: Добавляю инфу он ядре системы. Как в версии клиента пишет mcabber. Я меняю значение в версии клиента, а он мне всё равно то что по умолчанию указанно в переменной. Как это исправить? Ещё хорошо бы чтобы при необходимости можно было включить либо выключить инфу о ядре системы, ибо сменить на желаемую. Если нужна помощь, то помогу.

**Comment by 0ktav1us** [comment]
> > Original [issue 382](https://code.google.com/p/psi-dev/issues/detail?id=382) created by psi-plus on 2010-12-12T14:30:33.000Z:
> > Обсуждение плагина для гибкой настройки версии клиента
> 
> Привет Ri0n!
> Не пишет нужную информацию в плагине версии 0.0.18.
> Выбираю User Defined: Добавляю инфу он ядре системы. Как в версии клиента пишет mcabber. Я меняю значение в версии клиента, а он мне всё равно то что по умолчанию указанно в переменной. Как это исправить? Ещё хорошо бы чтобы при необходимости можно было включить либо выключить инфу о ядре системы, ибо сменить на желаемую. Если нужна помощь, то помогу.
> ########################
> РЕШЕНО, В ОС указал версию, по добавлению этого функционала всё в силе.

Подумал, template нужно добавить с переменой `stdout`  from **uname -a**``
