### ISSUE TITLE
0.16 Release

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#560]
Original [issue 552](https://code.google.com/p/psi-dev/issues/detail?id=552) created by psi-plus on 2013-07-31T08:58:51.000Z:

We are going to make 0.16 release of Psi and Psi+ in near future. 

Psi+ as always dev. So we just need a snapshot of current patches corresponding to new Psi version.

Justin is quite busy atm, so it's our task to review everything and add all critical fixes before release.

Here I suggest to write everything you want to see in 0.16 of Psi.

Currently we have next tasks to be done:
1) Finish with networkmanager in iris (it's my task)
2) Improve proxy settings management in iris and Psi
3) Move webkit from Psi+ to Psi. as always optional. but in any case it's pretty stable and usable for a long time. but we have to review themes javascript API
4) Review memory leaks fixes from Psi+ and move them to Psi.

**Comment by alexws54tk** [comment]
Очень сильно интересует пункт 6).
Хотеть возможность сборки при полном отсутствии qt4 в системе (in make.conf USE="-qt4 qt5").
Что для этого нужно помочь?

**Comment by Ri0n** [comment]
пункт 6 уже работает.
что бы собралось надо собрать qca c USE=qt5
обновить qconf до последней 9999 версии

**Comment by rapgro** [comment]
:+1:

**Comment by rapgro** [comment]
What about unbundling iris? It's important for Fedora.

**Comment by Ri0n** [comment]
Soon. I'm busy with fixing longstanding and annoying bugs now.
Then I'll review unbundled iris problem.

**Comment by Ri0n** [comment]
Updated list of tasks:
1) Finish with networkmanager in iris (it's my task)
2) Improve proxy settings management in iris and Psi
3) Fix all annoying webkit themes bugs (improve adium themes support. review/improve psi themes api)
4) Fix and enable stream management
5) compile with libiris shared lib (optional. bundled iris will be available for mac, windows and systems w/o shared libiris)
6) new caps version

**Comment by GreenLunar** [comment]
Please make the roster to respect RTL direction, before 0.16 is released. Currently, roster appears always from Left-to-right even when `qt_xx.qm` (be it Arabic, Hebraic, Persian) indicates Right-to-left. See #44.

I assume it is easy to fix.

**Comment by GreenLunar** [comment]
*EDIT: Maybe it is fixed in https://github.com/orgads/psi/commit/5e2dd5c6c7b33e89ad31b79e89d7ccbf737bbb9d, but I have no way to verify it.  If someone may send me a screenshot of dialogs listed in https://github.com/psi-im/psi/issues/44 in Hebrew, I would be able to verify it.*

**Comment by GreenLunar** [comment]
Please add Privacy Lists snippet to the Tip of the Day dialog, before 0.16 is released.  See https://github.com/psi-im/psi/issues/200

**Comment by Ri0n** [comment]
Updated list of tasks:
1) Finish with networkmanager in iris (it's my task)
2) Improve proxy settings management in iris and Psi
3) Fix all annoying webkit themes bugs (improve adium themes support. review/improve psi themes api)
4) Fix and enable stream management
5) compile with libiris shared lib (optional. bundled iris will be available for mac, windows and systems w/o shared libiris)
6) release new qconf [almost done]
7) RTL roster [almost done. have to figure out how to enable it automatically]

**Comment by GreenLunar** [comment]
> 7) RTL roster [almost done. have to figure out how to enable it automatically]

Maybe you need to refactor the roster.

In Qt software, you can use `QT_APP_NAME -reverse` (e.g. `qtnote -reverse` or `smplayer -reverse`) to see a reversed GUI, also in Psi, but roster is not affected as one might expect.

**Comment by Ri0n** [comment]
interesting..

8) fix file transfer problems if any

**Comment by Ri0n** [comment]
Updated list of tasks:
1) Improve proxy settings management in iris and Psi (we should have a task for this)
2) Fix all annoying webkit themes bugs (improve adium themes support. review/improve psi themes api)
3) Fix and enable stream management
4) compile with libiris shared lib (optional. bundled iris will be available for mac, windows and systems w/o shared libiris)
5) release new qconf [almost done]
6) RTL roster [almost done. have to figure out how to enable it automatically. check -reverse]

**Comment by rapgro** [comment]
> 4) compile with libiris shared lib (optional. bundled iris will be available for mac, windows and systems w/o shared libiris)
> 5) release new qconf [almost done]

Why not use cmake? cmake can also solve all bundling issues.
https://bugzilla.redhat.com/show_bug.cgi?id=1197370

**Comment by Ri0n** [comment]
We don't want too big changes for now. This release is as usually with qmake.

Next one will be purely Qt5 based oriented. with cmake or qbs.
At least we have one dev who is ready to port on qbs.

**Comment by rapgro** [comment]
qmake is not qconf. cmake works really well with Qt.
http://doc.qt.io/qt-5/cmake-manual.html

**Comment by Ri0n** [comment]
qconf is kind of addon for qmake-based build system.
cmake is absolutely different stuff .

**Comment by Ri0n** [comment]
Updated list of tasks:
1) Fix all annoying webkit themes bugs (improve adium themes support. review/improve psi themes api)

Deferred to next version:
1) compile with libiris shared lib (optional. bundled iris will be available for mac, windows and systems w/o shared libiris)
2) RTL roster [almost done. have to figure out how to enable it automatically. check -reverse]
3) Improve proxy settings management in iris and Psi (we should have a task for this)

**Comment by Ri0n** [comment]
WebKit stuff was heavily rewritten with introduction of web engine support.
Also it was decised to make often releases instead of fixing all possible bugs beore next release.

So I'm closing this one for now.

**Comment by Ri0n** [comment]
The release will be ready next a few days. May be even tomorrow.
