### ISSUE TITLE
[Cinnamon] Автоматическое открытие чата не отключается

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#579]
Original [issue 571](https://code.google.com/p/psi-dev/issues/detail?id=571) created by psi-plus on 2014-01-04T14:13:09.000Z:

При получении новых сообщений чат автоматически разворачивается.
Пробывал включать/отключать опцию:
Настройки -&gt; Чат -&gt; Открывать окно чата при получении новых сообщений

Результат тот же самый. 

ОС: Linux Mint 16 Cinnamon x64
Cinnamon version 2.0.14
Linux kernel 3.11.0-12
Psi+ v0.16.132 (2013-07-16) - из репозиториев

На windows 7 с аналогичной версией Psi+ такая проблема не наблюдается.

Очень прошу поскорее закрыть этот баг или выпустить патч.
Когда пишут десятки сообщений, вся остальная работа просто парализована.

Надеюсь на вашу помощь, спасибо!

**Comment by cavebeat** [comment]
https://github.com/linuxmint/Cinnamon/pull/4801 <-- should fix Psi+ stealing autofocus in Cinnamon

**Comment by tehnick** [comment]
https://github.com/linuxmint/Cinnamon/issues/7558

**Comment by tehnick** [comment]
Cписок захардкодженных приложений по состоянию на 22 ноября 2016 года:
```
org.cinnamon demands-attention-ignored-wm-classes ['skype', 'viber', 'quassel', 'retroshare', 'psi-plus', 'kadu', 'pidgin'] 
```

**Comment by tehnick** [comment]
Начиная с какой-то более свежей версии Cinnamon этот код выпилили.

**Comment by tehnick** [comment]
Простая тестовая утилита на Qt5 от @Ri0n : https://yadi.sk/d/SG8EHE1XRORe9A
Готовые статические сборки подходят для Ubuntu 14.04 (и новее), Windows 7 (а новее).

Для проверки алерта и поднятия окна нужно сразу после запуска программы свернуть главное окно и наблюдать за его поведением в панели задач в течение 11 секунд.

**Comment by artenaki** [comment]
> Предотвращение воровства фокуса, как правило дефолт во всех DE, но Cinnamon - исключение

Не только Cinnamon исключение, но и xfwm4 в Xfce крадет фокус (как минимум в Xubuntu 16.04). И [тестовая утилита](https://github.com/psi-plus/main/issues/579#issuecomment-461403507) это подтвердила. Сам мучаюсь давно с крысой, правда не в Psi. Обычно это проявляется, если запускаю какой-то жирный софт и пока он грузится, начинаю заниматься своими делами, а когда запустится, он крадет фокус. Или в Tixati раз в 1,5 месяца Donate окно на передний план выскакивает. Что интересно, как ни крутил настройки Xfce, становится только хуже. Хотя иногда захват фокуса бывает полезен (то есть предотвращение становится вредным). Например, если открываешь видеофайлы в файловом менеджере, видеоплеер сразу открывается, а не сворачивается, как это бывает в LXDE. Или текстовые файлы. В общем, сложная это тема передача фокуса, и не все так однозначно. Но точно желательно иметь SSD. И когда совсем уж внаглую выскакивает без запроса это плохо. По идее, это должно разруливаться именно приложением.

**Comment by Ri0n** [comment]
в кедах пока всё гут. рекомендую.
Ещё есть вариант натравить разработчиков Qt на разработчиков цинамона или наоборот.
