### ISSUE TITLE
Please implement XEP-280 Message Carbons

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#600]
Original [issue 592](https://code.google.com/p/psi-dev/issues/detail?id=592) created by psi-plus on 2014-09-22T00:20:05.000Z:

Зачем это нужно? Отменяет возню с приоритетами при том же логине на нескольких устройствах.

**Comment by Nyco** [comment]
Message carbons are mandatory if you want to have the same conversations on all your clients. This is especially useful when you switch all day long from a desktop client to a mobile client back and forth.

**Comment by rkfg** [comment]
Is this still relevant? Message carbons seem to be working in the latest version.

**Comment by drizt** [comment]
https://github.com/psi-im/iris/commit/17603cda4a7632a578d14c0abac6853b89073d43

**Comment by runderwo** [comment]
How does one disable this feature on the client side?  I had to disable carbons on the server side since I prefer to hand off conversations via priorities.
