### ISSUE TITLE
Support for Emojis (Emoticons)

### ISSUE THREAD

**Issue by Ri0n** [psi-plus/main#610]
Original [issue 602](https://code.google.com/p/psi-dev/issues/detail?id=602) created by psi-plus on 2014-11-24T09:36:54.000Z:

Feature to implement:
Support for Emojis

<b>Which clients already have it implemented:</b>
- Pidgin
- Trillian
- many more ...

May be this can be done by creating a emoji iconset which supports the standard emoji icons?

**Comment by Ri0n** [comment]
added to resources

**Comment by rapgro** [comment]
:+1:
