### ISSUE TITLE
Падение при выходе из приложения, если открыт диалог "О программе"

### ISSUE THREAD

**Issue by wadealer** [psi-plus/main#620]
Сабж. ОС Вин7 32, 449 билд Кукурузы.

**Comment by Vitozz** [comment]
Да, воспроизводится
(gdb) bt
#0  0x6e6ee344 in QCA::PluginInstance::~PluginInstance (this=0x8581488,
    __in_chrg=<optimized out>) at C:\build\libqca\src\qca_plugin.cpp:153
#1  0x6e6e85e0 in QCA::ProviderItem::~ProviderItem (this=0x85814b0,
    __in_chrg=<optimized out>) at C:\build\libqca\src\qca_plugin.cpp:254
#2  0x6e6bd08a in QCA::ProviderManager::unloadAll (this=0x358b68)
    at C:\build\libqca\src\qca_plugin.cpp:526
#3  0x6e6ba565 in QCA::ProviderManager::~ProviderManager (this=0x358b68,
    __in_chrg=<optimized out>) at C:\build\libqca\src\qca_plugin.cpp:313
#4  0x6e70bc7f in QCA::Global::~Global (this=0x358888,
    __in_chrg=<optimized out>) at C:\build\libqca\src\qca_core.cpp:116
#5  0x6e6929ed in QCA::deinit () at C:\build\libqca\src\qca_core.cpp:274
#6  0x6a243c60 in qt_call_post_routines () at kernel\qcoreapplication.cpp:302
#7  0x087cbc57 in QApplication::~QApplication (this=0x28fd68,
    __in_chrg=<optimized out>) at kernel\qapplication.cpp:1111
#8  0x005d9392 in PsiApplication::~PsiApplication (this=0x28fd68,
    __in_chrg=<optimized out>) at psiapplication.cpp:274
#9  0x007d2f2d in qMain (argc=1, argv=0x356798) at main.cpp:554
#10 0x008003b9 in WinMain@16 (instance=0x400000, prevInstance=0x0, cmdShow=10)
    at qtmain_win.cpp:131
#11 0x00bf881d in main ()

полный лог http://pastebin.com/U99a6CyQ

**Comment by Ri0n** [comment]
ещё актуально?

**Comment by Vitozz** [comment]
Для моих вендосборок - да, сборки зета не пробовал

**Comment by zet** [comment]
топикстартер, вроде, репортил о краше на сборке кукурузы.

**Comment by wadealer** [comment]
Я думаю, что и на сборках зета проблема будет, но проверить нет возможности - инсталеру больше года и там старый куца. Т.к. никаких фиксов по данному поводу сделано не было, то и проблема никуда не делась.
