### ISSUE TITLE
Configuring Psi ... Verifying Qt 4 build environment ... fail

### ISSUE THREAD

**Issue by xeverse** [psi-plus/main#624]
Reason: There was an error compiling 'conf'.  See conf.log for details.

Be sure you have a proper Qt 4.0 build environment set up.  This means not
just Qt, but also a C++ compiler, a make tool, and any other packages
necessary for compiling C++ programs.

If you are certain everything is installed, then it could be that Qt 4 is not
being recognized or that a different version of Qt is being detected by
mistake (for example, this could happen if $QTDIR is pointing to a Qt 3
installation).  At least one of the following conditions must be satisfied:

 1) --qtdir is set to the location of Qt
 2) $QTDIR is set to the location of Qt
 3) QtCore is in the pkg-config database
 4) qmake is in the $PATH

This script will use the first one it finds to be true, checked in the above
order.  #3 and #4 are the recommended options.  #1 and #2 are mainly for
overriding the system configuration.

**Comment by xeverse** [comment]
qtchooser --print-env
QT_SELECT="default"
QTTOOLDIR="/usr/lib/qt4/bin"
QTLIBDIR="/usr/lib"

**Comment by xeverse** [comment]
qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib

**Comment by xeverse** [comment]
please remove the issue

**Comment by rapgro** [comment]
Please reopen this issue. I can reproduce at Fedora 22 and with snapshot of rev 457. I do not know how to fix.

**Comment by Ri0n** [comment]
update qmake
