### ISSUE TITLE
OSX UI specific problem  - roster window not reopen after close

### ISSUE THREAD

**Issue by netnut404** [psi-plus/main#625]
If you close the contact list there is no way to bring it up without quitting the app and relaunching it.

can we add the option to open the contact list either from the menu across the top or the icon in the Dock ?

it kind of sounds like this issue  https://github.com/psi-plus/main/issues/413 but I could be wrong

Thanks..

Net Nut

**Comment by wadealer** [comment]
This was work some time ago but it has broken with some Qt updates. For now, I have experimental patch, but the latest OSX builds does not include it.

**Comment by klou** [comment]
Would be great to have this patch merged.

**Comment by tehnick** [comment]
Fixed long time ago.
