### ISSUE TITLE
Multiple tabs per contact in tabbed mode

### ISSUE THREAD

**Issue by rafis** [psi-plus/main#630]
I have multiple tabs per contacts in tabbed mode. It is very annoying, should be one contact = one tab. Seems other users reconnecting causing multiple tabs.

**Comment by Ri0n** [comment]
I don't understand what you mean. Could you attach screenshots with the problem and also tell me what is your version of Psi+.
Also make sure you have suitable tab settings in options->chat->use tabbed mode.

**Comment by wadealer** [comment]
rafis, you shoud enable "autojid" mode. http://pix.academ.org/img/2015/08/26/319e93f69251869233fa0646d7b9263f.png
http://pix.academ.org/img/2015/08/26/4db8c63a676b8045607c88f40f2eeb78.png
