### ISSUE TITLE
psi automatically switching tabs when chatting with google people

### ISSUE THREAD

**Issue by yokto** [psi-plus/main#634]
When chatting with people using some android clients and (I think the gmail website too), psi will always switch wildly between 2 tabs and barely let me complete a sentence. I think every time an event such as (... is typing) arrives it will switch. If I close anyone of the tabs, a new one will be opened immediately. Maybe it has something to do with the fact that the android/gmail client always shows as having 5-6 resources. Other clients such as gajim don't suffer from this problem when communicating with the the android/gmail client.

**Comment by liuch** [comment]
If I understand you correctly, see the last comment in #630.

**Comment by yokto** [comment]
It does seem to work and it's good enough for me. However I'm not sure it's a good fix since I assume everyone who wants to communicate with one of those clients, will have to find this (well hidden) checkbox.

**Comment by rapgro** [comment]
Strg+C (normally to copy marked text into clipboard) sometimes switches active tab. No idea if that's somehow related.

**Comment by wadealer** [comment]
rapgro, Are you use all-in-one mode? Ctrl+C is the shortcut to open new chat window with contact. So if roster has focus this may change active tab with focused contact. And this is unrelated to this issue. Closed.
