### ISSUE TITLE
Не работает выбор смайла

### ISSUE THREAD

**Issue by Bummelant** [psi-plus/main#636]
Не работает выбор смайла (и в чатах, и в конференциях).
При клике на смайл во всплывающем окошке поле ввода остаётся пустым.
При этом смайлы в чатах и конференфициях обрабатываются нормально, и отображаются графикой.
Кажется, подобное началось после недавнего обновления Qt.
Версия Psi+: 0.16.475 (2015-09-25)
ОС: openSUSE Tumbleweed x86_64 с KDE5
Версия Qt: 5.5.1

**Comment by Ri0n** [comment]
сейчас должно работать. поправлено одним из последних коммитов

**Comment by drizt** [comment]
Это бага Qt
