### ISSUE TITLE
APPCRASH on Windows

### ISSUE THREAD

**Issue by rafis** [psi-plus/main#637]
Psi+ KukuRuzo 0.16.469

This happens unexpectedly on random activity on PC and also started happing with 100% probability on exit. Perhaps it started happening after I've added 4+ active accounts.

```
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: psi-plus.exe
  Application Version:  0.0.0.0
  Application Timestamp:    00000000
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7601.19045
  Fault Module Timestamp:   56259295
  Exception Code:   c0000005
  Exception Offset: 00000000000194ba
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: abcc
  Additional Information 2: abcc8f7853b48d9807d6d51eb1fa5df9
  Additional Information 3: abcc
  Additional Information 4: abcc8f7853b48d9807d6d51eb1fa5df9
```

Where I can download debug build to send you detailed report?

**Comment by Vitozz** [comment]
First of all next time give us more information about your system and psi+. 
Your version of Windows is 7.
32-bit or 64?
Which version of psi+ do you use (webkit / not webkit / with new (sql) history)?.
I need to know this to make a debug build.
P.S. I know about this problem, but I can not reproduce it.

**Comment by rafis** [comment]
Windows 7 64-bit, not webkit, history saved in text files (I don't know how to turn on sqlite3 history).
Psi+ KukuRuzo 0.16.469-64 (2015-08-13), but error happens also on previous versions.

**Comment by Vitozz** [comment]
Debug version https://yadi.sk/d/zkIDpnHEmQkEY (In this version connection to server may not work)

**Comment by wadealer** [comment]
Is this still reproduces?

**Comment by Vitozz** [comment]
Версия х64 больше не выходит, думаю можно закрывать

**Comment by Vitozz** [comment]
KukuRuzo builds are not official and you use them at your own risk. X64 builds for Windows OS was a test and the test failed. In the near future will no longer x64 builds from KukuRuzo.
