### ISSUE TITLE
File transfer broken

### ISSUE THREAD

**Issue by ghost** [psi-plus/main#638]
I've been trying to send a file to a contact who uses Pidgin. I was unable to send the file after numerous attempts, even after turning off the firewall completely and rebooting the router. However, using Gajim on the same computer and the same account, the file sent first time successfully.

I am using v0.16.330 on Debian Jessie.

**Comment by chaotickjg** [comment]
As an addition to the previous report, it always seems to correctly detect that the file was accepted, but fails on connecting to my contact's client and says that it is unable to connect to peer.

I do not use a file transfer proxy. It is a direct connection.

**Comment by Ri0n** [comment]
I'll review all file transfer problems this week.

**Comment by Ri0n** [comment]
I can confirm. File transfer does not work from Psi to Gajim but works in back direction.
And I have fixed in-band file transfer.

**Comment by rapgro** [comment]
Maybe NAT? http://stackoverflow.com/questions/7601958/will-xmpp-work-in-a-nat-environment

**Comment by Ri0n** [comment]
I tried to start on the same desktop

**Comment by Ri0n** [comment]
fixed
