### ISSUE TITLE
psi-plus-icons-nonfree not installable (psi-plus Ubuntu PPA): overwrites goim2_maybe.png

### ISSUE THREAD

**Issue by cweiske** [psi-plus/main#639]
Installing `psi-plus-icons-nonfree` from the [Ubuntu PPA](https://launchpad.net/~psi-plus) fails, because it:
>  trying to overwrite '/usr/share/psi-plus/iconsets/clients/variants/goim2_maybe.png', which is also in package psi-plus-icons-clients 0.16.5049-0ubuntu1~ubuntu14.04.1~ppa1

Log:

```
$ apt-get install psi-plus-icons-nonfree
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  psi-plus-icons-nonfree
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 0 B/7836 kB of archives.
After this operation, 10.8 MB of additional disk space will be used.
(Reading database ... 975702 files and directories currently installed.)
Preparing to unpack .../psi-plus-icons-nonfree_16.02.03-0ppa1~trusty1_all.deb ...
Unpacking psi-plus-icons-nonfree (16.02.03-0ppa1~trusty1) ...
dpkg: error processing archive /var/cache/apt/archives/psi-plus-icons-nonfree_16.02.03-0ppa1~trusty1_all.deb (--unpack):
 trying to overwrite '/usr/share/psi-plus/iconsets/clients/variants/goim2_maybe.png', which is also in package psi-plus-icons-clients 0.16.5049-0ubuntu1~ubuntu14.04.1~ppa1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/psi-plus-icons-nonfree_16.02.03-0ppa1~trusty1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by tehnick** [comment]
Just remove all psi-plus-icons* packages.

**Comment by cweiske** [comment]
Are they deprecated?

Couldn't you mark `psi-plus-icons-nonfree` as conflicting with the other ones?

**Comment by tehnick** [comment]
> Are they deprecated?

Yes. IIRC, there are no such packages in official Psi+ PPA since November or October.

> Couldn't you mark psi-plus-icons-nonfree as conflicting with the other ones?

Yes, it is possible. But I need to find the list of removed packages for this.

**Comment by tehnick** [comment]
Could you show the output of command:
```dpkg -l | grep psi-plus```
in your system?

**Comment by tehnick** [comment]
It looks I have found the list of old packages:
```psi-plus-icons-activities
psi-plus-icons-affiliations
psi-plus-icons-clients
psi-plus-icons-emoticons
psi-plus-icons-moods
psi-plus-icons-roster
psi-plus-icons-system
```

There is no any need in such fragmentation.
All files are now in a single package: ```psi-plus-icons-nonfree```

**Comment by tehnick** [comment]
Fixed: https://github.com/tehnick/psi-plus-resources-debian/commit/8032ff055594d469a6447cb2de15ba85dd5f1723

**Comment by cweiske** [comment]
You forgot one: `psi-plus-icons-activities`

**Comment by tehnick** [comment]
Ok. Fixed.
