### ISSUE TITLE
Failed Patch: 0410-psi-activity-icons-and-description.diff !

### ISSUE THREAD

**Issue by parazyd** [psi-plus/main#640]
Trying to compile, patch 0410 fails. Please fix :)
Thanks in advance.

**Comment by parazyd** [comment]
Update:
With the latest commit, 0510-psi-css-style-sheet.diff fails now.

Installing with `emerge '=net-im/psi-9999'
Using rion overlay.

**Comment by parazyd** [comment]
0660-psi-custom-icons-size.diff fails with latest commit.

**Comment by parazyd** [comment]
1410-psi-tunable-chattoolbar.diff is an issue now :)

Sorry for all of this, hope I'm not a burden.

**Comment by Ri0n** [comment]
I'm aware of these all. I just have no time to fix all the patches.

**Comment by parazyd** [comment]
Latest commit allows a successful build :)
