### ISSUE TITLE
maximize button is missing for goupchat history

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#642]
maximize button is missing for goupchat history and there is a "?" what is it?

Image: 
https://camo.githubusercontent.com/37be96b02fc28f313abc206627b8fb1af5ce0fc5/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3130343733372f323138313334362f36313535316166632d393734632d313165332d386434632d6439313464633834353363312e706e67

Ticket originaly posted the 16 Feb 2014 on Psi (no ticket for Psi+ before...)
https://github.com/psi-im/psi/issues/122

**Comment by wadealer** [comment]
Are you talking about Conference logger plugin? Here is issue for it: https://github.com/psi-plus/main/issues/203

**Comment by Neustradamus** [comment]
The problem is always here: "?" and no minimize/maximize buttons.

**Comment by Neustradamus** [comment]
Currently missing in May 2020.
