### ISSUE TITLE
There is not history for room@conference.example.tld/user

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#643]
Like subject: There is not history for room@conference.example.tld/user.

Ticket originaly posted the 1 Feb 2014 on Psi (no ticket for Psi+ before...)
https://github.com/psi-im/psi/issues/115

**Comment by wadealer** [comment]
The histrory available with new-histroy-patch.
options.history.store-muc-private option should be set to True.

**Comment by Neustradamus** [comment]
There is a box in UI for simple user?

**Comment by Neustradamus** [comment]
Added: https://github.com/psi-plus/plugins/commit/e0e28bcfdc31f80f14fd15d6a07ca9e77342f791

**Comment by Neustradamus** [comment]
Can you reopen the ticket?
The problem is not resolved
@liuch ^^
Linked to https://github.com/psi-im/psi/issues/115

**Comment by rapgro** [comment]
Try Conference Logger Plugin or History Keeper Plugin. Go to Settings and Choose Plugins entry, then active those plugins with a click on the checkboxes.

**Comment by wadealer** [comment]
@rapgro these plugins cann't help with this issue. History Keeper Plugin is for REMOVING history. Conference Logger Plugin is for conference history, but not for private messages

**Comment by Neustradamus** [comment]
@wadealer I do not spam, I have only requested a reopen of the ticket because it is not closed.
If I create new tickets, it is for other points ^^
