### ISSUE TITLE
Перевод фокуса на окно чата/сообщения

### ISSUE THREAD

**Issue by SergeyShorin** [psi-plus/main#652]
в данный момент можно настроить программу так, что при получении нового сообщения/чата появляется окно.
но, если при этом пользователь переключится в другую программу (не закрывая сообщения) и придёт следующее сообщение в этот-же чат - то окно больше не "всплывает поверх других".
можно-ли сделать так, чтобы:
1. Либо окно при получении нового сообщения всегда всплывало поверх других, и получало системный фокус.
2. Либо чтобы была настройка "Окно чата поверх всех окон" (как это сделано для Ростера).
...ну и сделать эти функции включаемыми/выключаемыми в настройках.

**Comment by wadealer** [comment]
1. Такая опция есть: http://smages.com/images/pic2016042fdf.png

**Comment by SergeyShorin** [comment]
не  ссылка не открывается :-(

28.04.2016 11:58, Evgeny пишет:
>
>  1. Такая опция есть: http://smages.com/images/pic2016042fdf.png
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psi-plus/main/issues/652#issuecomment-215317220>
>

-- 
*Шорин Сергей Александрович*

**Comment by wadealer** [comment]
НУ что ж, не повезло тебе. Видимо, не достоин мои скриншоты смотреть. В настройках на странице "Чат" третья и четвертая опция сверху.

**Comment by zet** [comment]
А так? :) ![pic2016042fdf](https://cloud.githubusercontent.com/assets/16994/14881824/622c490e-0d3e-11e6-932c-43662094674e.png)

**Comment by SergeyShorin** [comment]
а какая версия у Вас в Windows?
у меня в Linux установилась "Psi+ v0.16.546.539 (2016-04-27)", а в 
Windows только:
"Psi+ v0.16.361 (2014-05-02) "

в Linuxе окно всплывает - всё ок!, а в Windows - нет...
подозреваю, что проблема в версии... ?

p.s. подскажите, где скачать последнюю версию (как в линуксе)?
пробовал ночные сборки, но ругается на отсутствие библиотеки libhunspell



28.04.2016 15:40, zet пишет:
>
> А так? :) pic2016042fdf 
> <https://cloud.githubusercontent.com/assets/16994/14881824/622c490e-0d3e-11e6-932c-43662094674e.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psi-plus/main/issues/652#issuecomment-215368646>
>

-- 
*Шорин Сергей Александрович*

**Comment by wadealer** [comment]
Все актуальные сборки под виндоус в персональных билдак Кукурузы. Есть на сурсфорже, есть на яндекс диске (ссылка в конференции).

**Comment by SergeyShorin** [comment]
я понимаю, что мои вопросы могут показаться тупыми...
но подскажите, какие архивы качать?
качаю "*Установщик (РЕКОМЕНДУЕТСЯ)
<http://sourceforge.net/projects/psiplus/files/MS-Windows/Installers/0.16/>*"
- качается "
psi-plus-0.16.361-win32-setup.exe
<https://sourceforge.net/projects/psiplus/files/MS-Windows/Installers/0.16/psi-plus-0.16.361-win32-setup.exe/download>
2014-05-03
- устанавливается версия 0.16.361 от 2014-05-02... запускаю - предлагает
перейти на страницу загрузки - соглашаюсь, перехожу на
https://sourceforge.net/projects/psiplus/files/MS-Windows/Installers/0.16/,
вижу там:
"Looking for the latest version? Download
psi-plus-0.16.545.535-webkit-win32.7z (2.2 MB)" - качаю. распаковываю из
архива в папку с программой - всё! перестала запускаться!

затем что? что на сурфордже, что на яндекс-диске - куча архивов.
из "Home  <https://sourceforge.net/projects/psiplus/files/>/ MS-Windows
<https://sourceforge.net/projects/psiplus/files/MS-Windows/> /
Personal-Builds
<https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/>
 / KukuRuzo
<https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/KukuRuzo/>
 / Night-Builds" качаю разные файлы... распаковываю в папку программы - не
запускается.

понимаю, что была замена a-spell на hunspell, но в какой версии? в каком
архиве?

Вы уж снизойдите до простых смертных, которые хотят пользоваться этой
программой - напишите алгоритм: что сначала качаем (предполагаю, что
всё-таки установщик), и как его обновляем (какие версии и в какой
последовательности устанавливаем/распаковываем? ...а какие можно и
пропустить...). ну или напишите ссылочки на библиотеки которые надо
дополнительно скачать - я не гордый, скачаю... (раз у Вас нет возможности
обновить инсталятор с 2014 года)

p.s. неужели никто до меня не задавал таких вопросов?

28 апреля 2016 г., 17:42 пользователь Evgeny <notifications@github.com>
написал:

**Comment by Vitozz** [comment]
А в конфу зайти спросить трудно? В корне яндекс диска лежат архивы (по 50мб которые) с полной рабочей сборкой пси+, смотрите последний по дате

**Comment by SergeyShorin** [comment]
ещё раз прошу прощения за тупые вопросы. видимо сегодня был не мой день.
наконец-то нашёл и скачал. спасибо Вам большое.

p.s. Было бы не плохо сделать ссылочку на корень Яндекс-диска рядом с
"установщик".
...чтобы таких вопросов не возникало.

Ещё раз спасибо!

28 апреля 2016 г., 21:33 пользователь Vitaly Tonkacheyev <
notifications@github.com> написал:

**Comment by SergeyShorin** [comment]
проблемма с выскакаванием окна на передний план (по приходу второго 
сообщения) остаётся актуальной!

поясняю:
1. Пользователю (П1) пришло первое сообщение от другого пользователя(П2) 
- окно чата появилось на переднем плане - всё ок!
2. Но П1 переключается на окно, в котором до этого работал (не закрывая 
окно чата с П2, ...ну надо ему так, что-то срочное)
3. П2 пишет П1 ещё одно сообщение - и вот в это время окно чата у П1 не 
выходит на передний план.

можно-ли сделать такие настройки:
"[Х] Выводить окно чата на передний план при приходе сообщения"
и как вариант добавить такую:
"[Х] Окно чата поверх всех окон" - как у ростера



28.04.2016 21:33, Vitaly Tonkacheyev пишет:
>
> А в конфу зайти спросить трудно? В корне яндекс диска лежат архивы (по 
> 50мб которые) с полной рабочей сборкой пси+, смотрите последний по дате
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psi-plus/main/issues/652#issuecomment-215468641>
>

-- 
*Шорин Сергей Александрович*

**Comment by wadealer** [comment]
Не воспроизводится твоя проблема. Выставлены те 2 галки, что на скриншоте и выставлена галка в событиях - открывать новые сообщения. Приходит первое сообщение - окно открывается. Потом открываю на передний план браузер. Приходит второе сообщение - чат выскакивает на передний план. Win7.
