### ISSUE TITLE
psi+ crashes regularly after update

### ISSUE THREAD

**Issue by jirislaby** [psi-plus/main#653]
I updated from snapshot 20160304 to 20160422 and I see regular crashes now. I am on openSUSE using packaged psi+.

#0  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (_q_value=@0x7f2a9044357f: -256) at ../../src/corelib/arch/qatomic_x86.h:219
#1  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=0x7f2a9044357f) at ../../src/corelib/thread/qbasicatomic.h:130
#2  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=0x7f2a9044357f) at ../../src/corelib/tools/qrefcount.h:67
#3  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=0x7f2a00003580, __in_chrg=<optimized out>) at ../../src/corelib/tools/qstring.h:1053
#4  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=0x7f2a00003580, __in_chrg=<optimized out>) at kernel/qhostaddress.cpp:93
#5  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (pointer=0x7f2a00003580) at ../../src/corelib/tools/qscopedpointer.h:54
#6  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=<optimized out>, __in_chrg=<optimized out>) at ../../src/corelib/tools/qscopedpointer.h:101
#7  0x00007f2a90d0f16d in QHostAddress::~QHostAddress() (this=<optimized out>, __in_chrg=<optimized out>) at kernel/qhostaddress.cpp:519
#8  0x0000000000529da6 in QList<QHostAddress>::node_destruct(QList<QHostAddress>::Node*, QList<QHostAddress>::Node*) (this=0x3a7cf88, from=0x7f2a00004050, to=0x7f2a00004050) at /usr/include/qt5/QtCore/qlist.h:463
#9  0x00000000005285b3 in QList<QHostAddress>::dealloc(QListData::Data*) (this=0x3a7cf88, data=0x7f2a00004040) at /usr/include/qt5/QtCore/qlist.h:834
#10 0x0000000000526c41 in QList<QHostAddress>::~QList() (this=0x3a7cf88, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qlist.h:796
#11 0x0000000000a270db in XMPP::NetInterfaceProvider::Info::~Info() (this=0x3a7cf70, __in_chrg=<optimized out>) at ../corelib/irisnetplugin.h:53
#12 0x0000000000a28d86 in QList<XMPP::NetInterfaceProvider::Info>::node_destruct(QList<XMPP::NetInterfaceProvider::Info>::Node*, QList<XMPP::NetInterfaceProvider::Info>::Node*) (this=0x7ffc766a9bb0, from=0x33d1b80, to=0x33d1b80) at /usr/include/qt5/QtCore/qlist.h:463
#13 0x0000000000a28683 in QList<XMPP::NetInterfaceProvider::Info>::dealloc(QListData::Data*) (this=0x7ffc766a9bb0, data=0x33d1b70) at /usr/include/qt5/QtCore/qlist.h:834
#14 0x0000000000a27b01 in QList<XMPP::NetInterfaceProvider::Info>::~QList() (this=0x7ffc766a9bb0, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qlist.h:796
#15 0x0000000000a27e32 in QList<XMPP::NetInterfaceProvider::Info>::operator=(QList<XMPP::NetInterfaceProvider::Info> const&) (this=0x3636a58, l=...) at /usr/include/qt5/QtCore/qlist.h:472
#16 0x0000000000a877db in XMPP::NetInterfaceManagerPrivate::do_update() (this=0x3636a40) at ../corelib/netinterface.cpp:335
#17 0x0000000000a87b18 in XMPP::NetInterfaceManagerPrivate::update() (this=0x3636a40) at ../corelib/netinterface.cpp:369
#18 0x0000000000a864fa in XMPP::NetInterfaceManagerPrivate::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x3636a40, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x2f6bfe0) at ./netinterface.moc:359
#19 0x00007f2a903c3c59 in QObject::event(QEvent*) (this=0x3636a40, e=<optimized out>) at kernel/qobject.cpp:1239
#20 0x00007f2a9427d87c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x2da09e0, receiver=receiver@entry=0x3636a40, e=e@entry=0x3717580) at kernel/qapplication.cpp:3716
#21 0x00007f2a94282986 in QApplication::notify(QObject*, QEvent*) (this=0x7ffc766aa2b0, receiver=0x3636a40, e=0x3717580) at kernel/qapplication.cpp:3499
#22 0x00000000006b9ffb in PsiApplication::notify(QObject*, QEvent*) (this=0x7ffc766aa2b0, receiver=0x3636a40, event=0x3717580) at psiapplication.cpp:398
#23 0x00007f2a90395be3 in QCoreApplication::notifyInternal(QObject*, QEvent*) (this=0x7ffc766aa2b0, receiver=0x3636a40, event=event@entry=0x3717580) at kernel/qcoreapplication.cpp:965
#24 0x00007f2a90397f06 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (event=0x3717580, receiver=<optimized out>) at kernel/qcoreapplication.h:224
#25 0x00007f2a90397f06 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x2d9f2f0) at kernel/qcoreapplication.cpp:1593
#26 0x00007f2a903983e8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1451
#27 0x00007f2a903e9013 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x2df5ab0) at kernel/qeventdispatcher_glib.cpp:271
#28 0x00007f2a8dd481a7 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#29 0x00007f2a8dd483d8 in  () at /usr/lib64/libglib-2.0.so.0
#30 0x00007f2a8dd4847c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#31 0x00007f2a903e941f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x2def7b0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#32 0x00007f2a9039352a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffc766aa200, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#33 0x00007f2a9039b1ed in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1229
#34 0x0000000000907fac in main(int, char**) (argc=1, argv=0x7ffc766aa4b8) at main.cpp:632

**Comment by Ri0n** [comment]
What do you mean by regular crashes? Psi does not work at all or crashes randomly after few minutes?

Also I need to know everything about your connection
1) type of connection wifi/wire
2) does it happen you randomly disconnected and reconnected to server with previous version or with any other application? and how often
3) any proxy in use
4) your xmpp server
5) connection from clean profile with default settings

**Comment by Ri0n** [comment]
I fixed one possible double free crash. May be it can help

**Comment by jirislaby** [comment]
Could you be more specific in which commit? I would definitely check it.

It crashes regularly on some event, i.e. the frequency is from every couple of minutes to hours. It crashed around 5 times a hour yesterday, no crash today yet.

1) wired connection. Pretty stable, I would say.
2) nope, I haven't noticed anything like that.
3) no proxy
4) njs.netlab.cz & talk.google.com. I am on those for years using psi+.
5) I will try this if your fix won't help. But given I am using this profile for almost decade, I doubt it will improve things.

**Comment by Ri0n** [comment]
https://github.com/psi-im/iris/commit/a524dc896620d59920d2606e12680f7dc9c49b07

**Comment by jirislaby** [comment]
I think we can close. No more crashes with snapshot from 20160501.
