### ISSUE TITLE
отправка сообщения нескольким контактам

### ISSUE THREAD

**Issue by SergeyShorin** [psi-plus/main#654]
можно-ли сделать отправку сообщения нескольким контактам? (не группе)
алгоритм:
1. в ростере выделяю несколько контактов, нажимаю Enter - появляется окно чата, в заголовке которого указаны все получатели сообщения (выделенные до этого в ростере).
2. пишу сообщение и отправляю его. сообщение уходит всем выбранным контактам.
3. как вариант - в окне чата рядом с именем активного контакта кнопка "+", по нажатию на которую выпадает список контактов с checkbox, в котором можно отметить кому будет отправлено это сообщение.

p.s. предвидя вопрос "как быть с историей сообщений?" - можно сделать настройку:
"[Х] не сохранять групповое сообщение в истории" или "[Х] сохранить групповое сообщение в истории каждого контакта"

p.p.s. ответы от контактов либо:
- принимать не в этот "групповой чат" а открывать для каждого ответа свою вкладку с каждым собеседником (если собеседник ответил)
- либо принимать в это-же окно чата.

**Comment by wadealer** [comment]
Этот функционал уже есть в менеджере контактов. Находится он в контекстном меню аккаунта в ростере. 
Хватит создавать задачи без обсуждения в конференции.
