### ISSUE TITLE
APPCRASH на windows 8.1 (x64) при закрытии psi

### ISSUE THREAD

**Issue by OvJS** [psi-plus/main#660]
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	psi-plus.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	00000000
  Имя модуля с ошибкой:	libstdc++-6.dll
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	00000000
  Код исключения:	c0000005
  Смещение исключения:	00000000000b17d3
  Версия ОС:	6.3.9600.2.0.0.768.100
  Код языка:	1049
  Дополнительные сведения 1:	1478
  Дополнительные сведения 2:	14780762679f60a2bd16062d8aee4f4c
  Дополнительные сведения 3:	c00a
  Дополнительные сведения 4:	c00ac03afae80cd43cd16fbfdb67be89

_psi-plus-0.16.469-all-in-one-setup_
_С версией 0.16.361 такого не наблюдается._

**Comment by Vitozz** [comment]
Ошибка известная, все сборки после 469 - кастомные, версии с qt4 с архитектурой х64 на некоторых пк падают при выходе (у меня не падают). Используйте сборки с яндекс диска, ссылки в теме конференции разработчиков. Я советую версию с qt5. Или пользуйтесь сборками Rion'а ссылки тоже в теме конференции
