### ISSUE TITLE
Нужен разработчик плагина для моего сервиса/Need dev plugin for my webserice $$

### ISSUE THREAD

**Issue by ad0true** [psi-plus/main#661]
Необходим опыт работы с написанием плагинов

+оплата сдельная, по договоренности
+возможно привлечение для создания следующих версий
+продукт будет open source

1 Необходимо использовать api xml/json сервиса
2 Обновлять данные через промежуток времени
3 Переносить контакты в отдельную группу
4 Уметь переименовать контакты (по возможности подменять статус иконку для нужных контактов)
5 Алерт оповещения -сообщения (вида OTR) в окно чата при необходимости
6 Использование настройки соединения из окружения (т.е. если в psi соединение через прокси-плагин должен работать через прокси)
7 Алерт оповещения при отправке сообщения в оффлайн или получения из оффлайна - при нахождении в базе
8 Билды необходимы как под win так и под nix

обращаться в джаббер ad0@zloy.im, либо сюда

Проект - вебсервис, создается чтобы очистить интернет от мошенников, а так же обезопасить пользователей от возможных проявлений

**Comment by ad0true** [comment]
We need a developer with experience in the creation of plug-ins

+ Piecework payment, by agreemen
+ Possible involvement to create the following versions
+ Product will be open source

1 You must use the api xml / json service
2 Refresh data after a time interval
3 Transferring contacts to a separate group
4 Be able to rename contacts (possible substitute for the status icon for the desired contacts)
5 Alert warning-messages (type of OTR) in the chat window if necessary
6 Use connection settings from the environment (that is, if psi connection via a proxy plug-in should work through a proxy)
7 Alert notification when sending messages offline or retrieve from offline - when in base
8 Builds needed as a win and a nix

contact the Jabber ad0@zloy.im, either here
The project - web service, created to purify the Internet from fraudsters, as well as to protect users against possible manifestations

**Comment by drizt** [comment]
Этого здесь не нужно.

**Comment by ad0true** [comment]
KukuRuzo сказал тут отписаться для девов кому будет интересно.
