### ISSUE TITLE
Psi+ crashes when receiving message from Pidgin (OTR enabled)

### ISSUE THREAD

**Issue by deselect** [psi-plus/main#663]
Hello.
To reproduce that bug you must follow next steps:
1. Set up Psi+ and Pidgin.
2. Start private conversation with OTR.
3. Send formatted message from Pidgin to Psi+ (for example, a hyperlink).
4. Get crash in libtidy.

Psi+ version: v0.16.563.582-webkit (22-08-2016)

**Comment by Ri0n** [comment]
I believe we should replace libtidy with something.

**Comment by rapgro** [comment]
Psi+ plugin does not work at all with OTR from Pidgin.

**Comment by deselect** [comment]
No, it works. Right now I am using it, it shows me that conversation is encrypted and verified. Maybe in fact it does not work, I do not know.

**Comment by deselect** [comment]
Bug is really annoying and it is critical vulnerability I think.
It can also crash even without OTR.
That's why I want to ask: is there a temporary workaround for it? Maybe I need to disable some option in my Psi+, maybe my companion has to disable something in his Pidgin? It is REALLY annoying to get crashes and to restart client & conversations.

**Comment by wadealer** [comment]
Try to disable this option: http://pix.academ.info/img/2016/11/01/0ad99eb5e5f1c58e7ae4e8945ba49975.png

**Comment by deselect** [comment]
Already disabled. Maybe disable something in Pidgin too?

**Comment by tehnick** [comment]
Do you use http upload plugin? Problem may be related with recent changes in processing of chat messages. But I haven't looked at code yet.

**Comment by deselect** [comment]
No, I do not use it.

**Comment by Ri0n** [comment]
Just tried OTR between pidgin and psi+ on Gentoo Linux and it works good regardless of formatting of messages

**Comment by deselect** [comment]
Psi+ version is the same?
Try it on Windows (I am using Windows 10). Try to copy & paste something in Pidgin chat window.

**Comment by Ri0n** [comment]
So we need 

1. versions of everything (OS and every dependency).
2. full backtrace
3. a way to reproduce

**Comment by Vitozz** [comment]
OS Windows 8.1, Psi+ v0.16.568.607-webkit (31-10-2016) (OTR 1.0.2) with Pidgin 2.11.0 (libpurple 2.11.0) (OTR 4.0.2) works perfectly

**Comment by deselect** [comment]
OS Windows 10 x64, Psi+ v0.16.563.582-webkit (22-08-2016) (OTR 1.0.2) with Pidgin 2.11.0 (libpurple 2.11.0) (OTR 4.0.2) on Windows 7 x64 crashes.
To get it crashed, just start private conversation and copy something (for example, hyperlink) in the Pidgin chat window and send.
Crash context (CPU, registers and stack): http://take.ms/T2NHE
Call stack (I know it's not OK because StackWalk64 does not work OK): http://take.ms/OQEUs

**Comment by deselect** [comment]
Still unreproducible? Maybe some more info?
Caught that with Gajim with OTR too.

**Comment by Vitozz** [comment]
Yes, really it crashes when psi+  received multi-line message (win32)

**Comment by Vitozz** [comment]
Fixed

**Comment by tehnick** [comment]
https://github.com/psi-im/plugins/commit/d410168acc7c188ebf2b1f27759cc610896f0613
