### ISSUE TITLE
URL not complete

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#664]
You can see on the screenshot that the link is not complete.
There is a problem with ' and maybe other too.

![linkbugpsi](https://cloud.githubusercontent.com/assets/104737/19447163/88ed8bda-949c-11e6-86e2-255324971406.png)

**Comment by Ri0n** [comment]
I can't reproduce it. Probably it as badly formatted by remote side

**Comment by Neustradamus** [comment]
I close this ticket ^^
