### ISSUE TITLE
x86_64 builds missing

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#668]
Since some weeks, there is only x86 "Qt5" builds.

Can you add for 64 bit machines?

**Comment by Vitozz** [comment]
X64 version of Psi+ for Windows (from KukuRuzo) is no longer exists. And will not be updated. Try to use x86 version or try to use builds from Rion (all links can be found in the topic of psi-dev conference).

**Comment by tehnick** [comment]
[11:07:59] \<Neustradamus\> I would like to comment on: https://github.com/psi-plus/main/issues/668
For users who would like to test, there are not official builds here:
\- Psi: https://sourceforge.net/projects/psi/files/Experimental-Builds/MS-Windows/tehnick/
\- Psi+: https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/tehnick/
[11:08:15] \<Neustradamus\> but I can not... :/

**Comment by tehnick** [comment]
[11:11:04] \<rion☫\> Neustradamus: Psi 1.1 official windows build will be x64 only

https://sourceforge.net/projects/psi/files/Experimental-Builds/MS-Windows/rion/
https://sourceforge.net/projects/psi/files/Psi/1.1/
