### ISSUE TITLE
Constant crashes in font selection dialog

### ISSUE THREAD

**Issue by ghost** [psi-plus/main#670]
If you try to select font in fonts selection dialog, psi-plus crashes almost every time.
Distro: Ubuntu 16.04
Psi-plus version: v0.16.568.604 (2016-10-22)

**Comment by Ri0n** [comment]
I can't reproduce this with the latest WebKit version compiled from git with Qt5.6.
Not sure about any other configurations.

Do you have a backtrace?

**Comment by nekomiko** [comment]
I have apport crash report, which contains stacktrace, coredump and other information.
[_usr_bin_psi-plus-webkit.1000.crash.zip](https://github.com/psi-plus/main/files/694723/_usr_bin_psi-plus-webkit.1000.crash.zip)

**Comment by nekomiko** [comment]
[stacktrace.txt](https://github.com/psi-plus/main/files/694906/stacktrace.txt)
Sorry, apport stacktrace was truncated up to first 2000 entries, here is full stack trace. Is it okay that it 41669-entries long?

**Comment by nekomiko** [comment]
Currently bug can be reproduced by following sequence of actions on my system:
1. Preliminary have default font "Sans Serif 9" (which is alias to "DejaVu Sans" "Book" on my system) used for list of contacts.
2. Click on "Noto Serif Thai" when choosing contact list's font.
3. Psi+ immediately crashes.

**Comment by Ri0n** [comment]
It's definitely a Qt bug. We can't do anything about it. Even providing Psi version based on Qt5 is hardly an option since Xenial has too old Qt5.

**Comment by nekomiko** [comment]
>Even providing Psi version based on Qt5 is hardly an option since Xenial has too old Qt5.
Why 5.5.1 is too old? I just build from git with xenial's Qt 5.5.1 and it looks like in solves the problem.

**Comment by nekomiko** [comment]
Build in ppa has been updated and I no longer having this problem. IDK how to stably reproduce this crash anymore. Maybe it will return.

**Comment by nekomiko** [comment]
Please close. I no longer having this issue with current Qt 5.5.1 builds.
