### ISSUE TITLE
Psi+ PMs anyone who writes ?OTRv23? in a MUC

### ISSUE THREAD

**Issue by bowlofeggs** [psi-plus/main#672]
I learned today in the Conversations MUC that if any user starts a message with ```?OTRv23?```, my Psi+ client will PM them some sort of OTR message (I can't decrypt it so I don't know what it is). It's pretty easy to reproduce, just enter an MUC that has someone using Psi+ in it, and type ```?OTRv23?testing``` and you'll get a PM.

Additionally, the Psi+ client will not render the messages that start that way.

**Comment by bowlofeggs** [comment]
Additionally, the Psi+ client will not render the messages that start that way.

**Comment by moparisthebest** [comment]
It's also not only if the message starts with that, but also if the message contains that string at all, which is completely wrong behavior of course.

**Comment by Ri0n** [comment]
Yep weird. Any OTR developer here? =)

I believe Psi should reply with such crap if and only if it's a real otr message (successfully decrypted and handled)

**Comment by ValdikSS** [comment]
Fixed.

**Comment by Neustradamus** [comment]
Thanks a lot @ValdikSS :)
