### ISSUE TITLE
XEP-0384: OMEMO Encryption

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#673]
Can you add OMEMO Encryption support?

https://conversations.im/omemo/
https://xmpp.org/extensions/xep-0384.html

https://github.com/psi-im/psi/issues/252
https://github.com/psi-plus/plugins/issues/10

**Comment by Neustradamus** [comment]
For example, Gajim has support:
- https://github.com/omemo/gajim-omemo
- https://dev.gajim.org/gajim/gajim-plugins/wikis/OmemoGajimPlugin
- https://packages.debian.org/stretch/gajim-omemo
- https://launchpad.net/ubuntu/+source/gajim-omemo

**Comment by jabbertw** [comment]
Bump.
OMEMO would be great.
A few years ago Psi+ was the most advanced client with all the features ahead, too bad to see
it now half abandoned and lagging behind.

**Comment by Ri0n** [comment]
@jabbertw, it's very easy to solve. Just join our team and help with development. Ask your friends to join too.
No one wants to use jabber nowdays. Just some old geeks are still dancing around old good Jabber.
Currently we have just two low-level developers including me. And both have very limited time for the project bacause of family, work, some own business etc.
I have development plans for years ahead but w/o some help it's nothing.

And you know what? Every time I ask people to join they decline. Nobody wants to contribute.

**Comment by Ri0n** [comment]
OMEMO won't be available for next release which is planned really soon.

**Comment by gerroon** [comment]
@Ri0n 

Thankjs for considering. I think that most people are not really devs. For instance i would like to help but I am no dev.

**Comment by ValdikSS** [comment]
I offer $1000 bounty for OMEMO encryption support in Psi+. This should be implemented either directly in a code or as a plugin, and should be fully compatible with the specification and with existing implementations. It should work with multiple connections on one account (multiple resources).

**Comment by TheRojam** [comment]
+1

**Comment by Neustradamus** [comment]
@TheRojam: OMEMO has been added but not perfect yet, ping @stigger.

**Comment by Neustradamus** [comment]
For all people, have you updated your Psi/Psi+?

I would like feedbacks from all users for OMEMO:
- Between Psi, Psi+, and other OMEMO XMPP clients
- OMEMO detection (grey icon / color icon)
- Secure chat (1:1)
- Secure mucroom
- New fingerprints detection
- OMEMO option possibilities (Options->Plugins->OMEMO options), all are good?
-- "Clear devices" and "Refresh" buttons in "Manage Devices" are missing (https://github.com/psi-im/plugins/issues/38)
-- Impossible to remove fingerprints of contacts (https://github.com/psi-im/plugins/issues/37)
-- Regenerate "Own fingerprint" is missing (https://github.com/psi-im/plugins/issues/36)

In the same time:
- OTR feedback too
- GnuPG feedback too

Thanks in advance.

**Comment by wadealer** [comment]
Why do you spamming the same text? Are you sick? Stop this shit please.

ср, 20 Мар 2019, 17:54 Neustradamus <notifications@github.com>:

**Comment by naodesu** [comment]
I don't actually understand how to work with this plugin...
I can't find the way to enable OMEMO in chat window.
Plugin options shows own fingerprint but thats all, "Fingerprints" tab is empty.
Plugin is enabled in settings.

Psi+ v1.4.720 (2019-06-09, Psi:6b105d15, Psi+:280e8c3)
![screenshot](https://user-images.githubusercontent.com/38212/59471079-676ae800-8e53-11e9-86ef-9deedb84be18.png)

**Comment by tehnick** [comment]
@naodesu You need add OMEMO plugin button on toolbars for private and group chats in Psi+ Options Dialog.

**Comment by naodesu** [comment]
@tehnick Thank you. Found it. But honestly, it's pretty obscure for new Psi+ users...

**Comment by tehnick** [comment]
By idea it should appear on these toolbars automatically after installation and first enabling of plugin in Options Dialog. But unfortunately it does not work as expected.

**Comment by Neustradamus** [comment]
The problem is specified to chat window.
I have already informed team several times.
One day, I hope a solution.

Look the difference for all possibilities:
Example 1:
1/ Open a mucroom
2/ Go to Options -> Toolbars -> Groupchat -> remove OMEMO Plugin action -> Apply
The OMEMO Plugin button is removed :)
Add a new time -> Apply
The OMEMO Plugin button is here :)

Example 2:
1/ Open a chat with a contact
2/ Go to Options -> Toolbars -> Chat -> remove OMEMO Plugin action -> Apply
The OMEMO Plugin button is not removed :(

No live refresh for CHAT window but GROUPCHAT window no problem.

**Comment by Neustradamus** [comment]
Toolbar problem with chat window has been solved!
- https://github.com/psi-im/psi/issues/362

**Comment by Neustradamus** [comment]
Dear all Psi/Psi+, and OMEMO users,

Several years after the OMEMO support beginning, can you update your Psi+ version and can you check all?

There are a lot of improvements since beginning.

Currently, I need some help.
It will be nice to confirm bugs, it is important to have OMEMO bug fix.
Several people confirm, it is better than only one or two.

I have done a big ticket about OMEMO here:
- https://github.com/psi-im/psi/issues/909

Any help is welcome to confirm all bugs, please read OMEMO tickets...

OMEMO works:
- Chat (1:1)
- Groupchat (in a Protected MUC Room)

If you can test with several XMPP Accounts in the same Psi+ client, it will be nice.

For example:
- user1@domain1.tld
- user2@domain2.tld
- user3@domain3.tld
- Or different XMPP Accounts on the same XMPP Server...

For example, you must to add your different XMPP Accounts in each XMPP Accounts:
- user1@domain1.tld | in contact list, you must to add user2@domain2.tld and user3@domain3.tld
- user2@domain2.tld | in contact list, you must to add user1@domain1.tld and user3@domain3.tld
- user3@domain3.tld | in contact list, you must to add user1@domain1.tld and user2@domain2.tld

Talk between all XMPP Accounts to add OMEMO fingerprints, only after, you can see for a Protected MUC Room.

You can create and join a Protected MUC Room (configuration: password + anyone see XMPP Address / Jabber ID) with all your XMPP Accounts (all XMPP Accounts must to know all other XMPP Accounts which will be in the Protected MUC Room), you can send messages, to beginning without OMEMO, verify all is good and now enable OMEMO and see the bugs).

Thanks in advance.

All latest Psi+ (installer and portable) versions are on MEGA, done by @Vitozz:
- https://mega.nz/folder/uhEigTJR#W6lQXiJ_pGbsO1tJn5s7UA

On Sourceforge, only a recent installer:
- https://sourceforge.net/projects/psiplus/files/Windows/Personal-Builds/KukuRuzo/

**Comment by strunzoz** [comment]
@Neustradamus to that matrix must be included Resources and Priorities
