### ISSUE TITLE
History bug

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#674]
When we :
- "Send Message" to a contact, the message is not saved in history
- "Open Chat Window" to a contact, the message is saved in history

Note: The contact with Psi+ has good messages in history.

![psi bugs](https://cloud.githubusercontent.com/assets/104737/22861506/98b10d1e-f11a-11e6-8861-3a3a64a4b50c.png)

**Comment by Neustradamus** [comment]
1/
<message to="user2@example.tld" id="aad1a">
<subject></subject>
<body>test message 1702132050
</body>
</message>

2/
<message to="user2@example.tld" type="chat" id="xxxxx">
<body>test chat
</body>
<active xmlns="http://jabber.org/protocol/chatstates"/>
<request xmlns="urn:xmpp:receipts"/>
</message>

<message to="user1@example.tld/Psi+" from="user2@example.tld/Psi+" id="yyyyy">
<received xmlns="urn:xmpp:receipts" id="xxxxx"/>
</message>

--------
user1@example.tld : Sender
user2@example.tld : Recipient

We can see in the same time that:
<active xmlns="http://jabber.org/protocol/chatstates"/>
<request xmlns="urn:xmpp:receipts"/>
is missing for first choice!

**Comment by liuch** [comment]
Fixed: https://github.com/psi-im/psi/commit/533ca0ef26b16ff848c8f83482a4ac6f9defd38c
