### ISSUE TITLE
Spam bot messages in triplicate

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#675]
When a spam bot message arrives, it is in triplicate:
- Two in: "Send Message" window
- One in: "Open Chat Window" window

In history, I have:
|YYYY-MM-DDTHH:MM:SS|1|from|N---|...
|YYYY-MM-DDTHH:MM:SS|5|from|N---|...
|YYYY-MM-DDTHH:MM:SS|0|from|N---|...

"..." the spam message.

XML Console (UsernameX is different for each message but same JID):
- Spammer 1:
```
<message type="chat" to="user@example.tld" from="spammer1@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

```
<message type="headline" to="user@example.tld" from="spammer1@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

```
<message to="user@example.tld" from="spammer1@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

- Spammer 2:
```
<message type="chat" to="user@example.tld" from="spammer2@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

```
<message type="headline" to="user@example.tld" from="spammer2@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

```
<message to="user@example.tld" from="spammer2@example.tld/Ressource">
<nick xmlns="http://jabber.org/protocol/nick">usernameX</nick>
<body>spam message</body>
</message>
```

**Comment by Ri0n** [comment]
and what do you want to do with that?

**Comment by Vitozz** [comment]
It's not a bug. Spambot sends you three kind of messages to avoid spamblocking.

**Comment by Neustradamus** [comment]
Can you add options for not received messages from and remove options to send :
- "Send Message" window
- "Open Chat Window" window

message type="chat"
message type="headline"
message

**Comment by wadealer** [comment]
No we cann't

**Comment by Ri0n** [comment]
@Neustradamus , if you have some feature in mind or noticed a bug please discuss this in our conference. Sometimes It's really hard to understand from your reports what you want and what benefits it brings to everyone else.
Thanks.
