### ISSUE TITLE
 HTTPS for website

### ISSUE THREAD

**Issue by oodbur** [psi-plus/main#680]
the website psi-plus.com should get HTTPS enabled and then maybe offer some secure hash values of source code release files.

**Comment by tehnick** [comment]
I have accidentally found useful tool: https://packages.debian.org/sid/sslh
It allows to use https and xmpp servers at 443 port simultaneously.
So we may use Let's Encrypt and set up https access to http://psi-plus.com/

**Comment by tehnick** [comment]
Done.
https://psi-plus.com/
https://psi-im.org/
