### ISSUE TITLE
PT-BR translation

### ISSUE THREAD

**Issue by robertboyl** [psi-plus/main#685]
Pls inform where I can send a correction regarding Brazilian Portuguese translatin of PSI+.

Tried to write to translator shorterfire at gmail, but no reply.

Thanks!

**Comment by Ri0n** [comment]
Hi 
it's here https://www.transifex.com/tehnick/psi-plus/dashboard/

**Comment by Ri0n** [comment]
You can join our team there. https://www.transifex.com/tehnick/psi-plus/language/pt_BR/

**Comment by robertboyl** [comment]
Thanks, but a bit out of time now. It was just a small correction. I sent to what appears as BR translator on the interface, shorterfire at gmail.com, but no reply.

Do you know if theres an active PT-BR translator I can email with small suggestion?

Thanks!

**Comment by Ri0n** [comment]
Hi! Responsible for translation person is on vacation now. We are waiting for him in a week vor so.
I dont know uf I have permissions to change translations, but I'll check.

**Comment by tehnick** [comment]
@robertboyl Hi. If you want to fix one or two words, you may just write them here. But for more amount of changes please join to our translation team:
https://www.transifex.com/tehnick/psi-plus/language/pt_BR/

**Comment by tehnick** [comment]
As for translations for Psi, I am going to make a script for automatic updation of them basing on Psi+ translations.

**Comment by tehnick** [comment]
Open new issue when you will be ready.

**Comment by robertboyl** [comment]
Thanks, butthe guy who does PT-BR is still active, just travelling, right?

Where someone is typing, inside a chat window, it shows "Bobestá digitando" (Bobis typing) instead of "Bob está digitando". That word "está" is glued to person's name.

Thanks.

**Comment by tehnick** [comment]
> Thanks, butthe guy who does PT-BR is still active, just travelling, right?

I do not know. Last time he updated Psi+ translation about year ago.

> That word "está" is glued to person's name.

Fixed.

Thanks for the bug-report.

**Comment by robertboyl** [comment]
Thanks a lot!!

**Comment by robertboyl** [comment]
Hi!

Ideas when new version will be out with this fixed?

Thanks!
Rob

**Comment by Ri0n** [comment]
I see a lot of requests for a new version. I'll try to collect all the fixes for 1.3 and release it this weekend

**Comment by robertboyl** [comment]
Wow, thats gotta be the fastest answer I ever got in my lifetime :) PSI+ will alert about new version? Thanks.

**Comment by Ri0n** [comment]
it should. In any case we hae nightly builds where everyting is fixed already.

**Comment by robertboyl** [comment]
Thanks. pls tell me when its out so I can see if it autodetects? Im on 0.16.361

btw here is best place to download it in english language web page?

Thanks!

**Comment by tehnick** [comment]
> Im on 0.16.361

It is too old version.

Last stable release of Psi: https://sourceforge.net/projects/psi/files/Psi/1.3/

Psi+ uses rolling release development model, regular builds you may found here:
https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/tehnick/
https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/KukuRuzo/

And stop use this issue for unrelated questions please.
Join to our XMPP conference for a feedback.

**Comment by robertboyl** [comment]
Hi,

Thanks, but Im talking about PSI+, not PSI.

All I wanted is to know when the new release with correction I sent will be
out.

- Rob

2017-10-04 6:00 GMT-03:00 Boris Pek <notifications@github.com>:

**Comment by tehnick** [comment]
@robertboyl It is already there since 10 Jul.

**Comment by robertboyl** [comment]
Hi,

Mine didnt autoupdate. Pls guide me to the windows installer.

In sourceforge installer folders latest is 0.16.

here also
http://psi-plus.com/wiki/ru:downloads#%D0%B4%D0%B8%D1%81%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%B8%D0%B2%D1%8B_psi

Thanks

2017-10-06 13:35 GMT-03:00 Boris Pek <notifications@github.com>:

**Comment by wadealer** [comment]
@robertboyl http://pix.academ.info/img/2017/10/07/245d193ef7fd67451d96b9223bd3ce70.png

**Comment by robertboyl** [comment]
That one I saw, but its not installer, its 7z. How do I install it?

As I wrote in the installer folder, theres just old version.

In your wiki also...


2017-10-06 15:45 GMT-03:00 Evgeny <notifications@github.com>:

**Comment by wadealer** [comment]
Wiki already fixed. Now it points to new installers.

**Comment by tehnick** [comment]
@robertboyl I gave you enough links in https://github.com/psi-plus/main/issues/685#issuecomment-334093206 . Just open them and read info there.

> In your wiki also...

We have a lot of outdated documentation in wiki and in other places. Some of it could be fixed quite fast, but not all.

@wadealer KukuRuzo раньше всегда протестовал, когда мы предлагали его сборки называть официальными и давать ссылки на них.

**Comment by wadealer** [comment]
@tehnick да, я в курсе, много раз с ним на эту тему говорили. Тем не менее, в том же Вконтакте линки именно на его сборки. Пусть и в вики будут. Давать линк на сбоку zet'а трехлетней давности бессмысленно. К тому же в самом каталоге со сборками на сурсфорже ясно написано, что эти сборки неофициальные.

**Comment by tehnick** [comment]
@wadealer Добавил [README.txt](https://sourceforge.net/projects/psiplus/files/MS-Windows/Installers/), но не умеющим читать это не поможет...

**Comment by robertboyl** [comment]
I installed the new version, it seems it installed separately from my PSI+ 0.16. It didnt upgrade it, installed to other path \Psi-plus-qt5... Just FYI... Its a bit confusing, ideal if it just upgraded/detected previous path (and also informed of new version, which didnt happen). And when I try to execute psi-plus.exe (Win 10), nothing happens.

Should I have installed it to same path as old one?

Thanks

PS - if you prefer some other place to discuss this, pls tell me where, I prefer emai/forum than chat.

My goal still to see the language fix and upgrade a few client machines, but ideally in easy way...

**Comment by robertboyl** [comment]
*Thanks. Well, I reimained on 0.16 because the installer never informed on
new version and online things were outdated. Not my fault imho.*


*No worries, I will uninstall old version, install new one and reconfig
accounts.*

**Comment by Vitozz** [comment]
My installer is completely incompatible with the old version. I'm using another program to create an installer. I'm using a different version of Qt 5.5 instead of 4.8.7. I use a different spell checker, hunspell instead of aspell. In my installer 4 versions of the program are available. My installer checks for the existence of previous versions of only my installers. Unfortunately, it seems very likely that there will no longer be any official installers of Psi+ under OS Windows.

**Comment by robertboyl** [comment]
Thanks a lot. I uninstalled old version, installed new (KukuRuzo build) and it picked up all settings :)

Can close this.
