### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by lolakle91** [psi-plus/main#687]
Friends i need help in making site in reality. What to do? Im a begginer! Can you help me?
1. Make it to the host to show in the audience
2. To make flashplayer on it.
Thank you for help
test site
<!DOCTYPE html>
<html>
<head>       
<title>Поехали!</title> 
</head>    
<body>       
<h1>Заголовок</h1>       
<p>Язык HTML достаточно простой. Сначала может показаться, что в нём слишком много тегов. Но не волнуйтесь. Мы постепенно познакомимся с ними на практике. А на практике всё запоминается легко.</p>
<p>Посмотрите на нижнюю часть мини-браузера, там вы увидите окошко с задачами, которые нужно выполнить, чтобы пройти задание.</p>
<p>Измените строку "Заголовок" на "Поехали!" внутри h1. Если вы всё сделали правильно, то загорится кнопка "Следующее задание".</p>
</body>
</html>

**Comment by Ri0n** [comment]
Spam

**Comment by zet** [comment]
Отправил его в баню https://github.com/organizations/psi-plus/settings/user_blocks

**Comment by Vitozz** [comment]
Zet, Were are you disapeared? We need you!
