### ISSUE TITLE
Latest vesrions of psi+ can work with server JABBER.RU

### ISSUE THREAD

**Issue by weekends** [psi-plus/main#689]
Can't work with jabber.ru servers, if you have roster with alot of contacts (at less 200). With version 0.16.475 all work fine, with versions 1.0.116 and later psi+ connect to server and immediately disconnect.

**Comment by Ri0n** [comment]
Well I suppose it depends on connection speed. Probably stream management can't get response in time.
Currently Psi doesn't have an option to disable stream management to check this theory.
But if you can patch sources, try to change SM_TIMER_INTERVAL_SECS constant to something bigger.
Or you can change NS_STREAM_MANAGEMENT to something invalid, so stream management will be disabled.

**Comment by liuch** [comment]
> Currently Psi doesn't have an option to disable stream management to check this theory.

Hmm. There is such option in the account settings.

**Comment by Ri0n** [comment]
Sorry. I missed it :)
Yes it's there.

**Comment by liuch** [comment]
@weekends Can you check it now with the last version?

**Comment by Ri0n** [comment]
@weekends, if with the latest version it's still an issue, just reopen this bug and provide us with more details.
