### ISSUE TITLE
Psi+ leavse MUC when MUC window closed

### ISSUE THREAD

**Issue by p5n** [psi-plus/main#691]
Keyboard shortcuts can be rebind to hide window instead of closing, but it always leave chat on closing window with mouse.

It is not expected behaviour I think. At least hide-on-close option is needed for MUC.

**Comment by wadealer** [comment]
Use Extended options plugin

03 Авг 2017 г. 18:00 пользователь "Sergej Pupykin" <notifications@github.com>
написал:

**Comment by p5n** [comment]
Cannot find it

See something for tabs (middle and double click action), but it looks like it does not work on separate windows.

**Comment by wadealer** [comment]
Nobody uses separate windows today. So there is no such options for this mode. It's a good time to switch to tabbed mode.

**Comment by p5n** [comment]
I use it with tiling WM so it is much more convenient then psi+ tabs. May be just switch default behaviour to leave chat only when user asks to leave it?

**Comment by Vitozz** [comment]
Fixed in 6f5da63c357ee292ef66b61aeff4f16d3db51aa7
