### ISSUE TITLE
RFE support for qtkeychain to store passwords more securely into kwallet or gnome-keyring

### ISSUE THREAD

**Issue by rapgro** [psi-plus/main#692]
https://github.com/frankosterfeld/qtkeychain
https://www.kde.org/applications/system/kwalletmanager/
https://forum.kde.org/viewtopic.php?f=83&t=38997

**Comment by Ri0n** [comment]
Initial support added to upstream.

**Comment by Ri0n** [comment]
implemented. will be available with 2.0 release.

**Comment by rapgro** [comment]
What to do if qtkeychain is not available, maybe in a Gtk-based desktop system? Does the user need to recompile the whole psi-plus?

**Comment by Ri0n** [comment]
exactly. 
I believe those guys who don't use full-featured desktop environment from distro maintainers always compile something by themselves. So it's Ok.

**Comment by Ri0n** [comment]
Added runtime option to disable keychain
