### ISSUE TITLE
Annoying dialog "Encryption is enabled but no QCA keystore manager is not available..."

### ISSUE THREAD

**Issue by boospy** [psi-plus/main#697]
On every start of the programm i must set my gpgkey in userprofile again. It is not dependig on the desktop, also with Unity on other friends. I have kde-neon. 
PSI-Version: Psi+ v1.2.97 (2017-10-05, Psi:ce96da29, Psi+:b7f8ecd)
I get this errormessage on every start:
Encryption is enabled but no QCA keystore manager is not available
Thank you

**Comment by boospy** [comment]
I've downgraded to Psi+ v0.16.330 (2014-04-05) in Ubuntu Xenial and everything works fine. So i see there is a problem with newer versions

**Comment by tehnick** [comment]
This is not a real bug. You may just ignore this useless dialog. I'll remove it soon and will update the packages in PPA.

**Comment by boospy** [comment]
ok thank you, can you answer me here when you updated it? 
Thanks a lot!

**Comment by tehnick** [comment]
Fixed in https://github.com/psi-im/psi/commit/e5599165f93fcfefa74e7bfb475b6653348eb79b.

**Comment by boospy** [comment]
It works perfectly! Thanks for the fast fix!
