### ISSUE TITLE
Quick add conference to bookmarks

### ISSUE THREAD

**Issue by DaarkWel** [psi-plus/main#703]
Please make "add to bookmarks" in context menu of conference name in roster.

**Comment by tehnick** [comment]
![screenshot_20171213_002905](https://user-images.githubusercontent.com/441190/33909699-91139384-df9d-11e7-8705-560af10d36df.png)

**Comment by DaarkWel** [comment]
Yes, I know. But adding to bookmarks from context menu would be much faster if I need to add several conferences. And I'd also add there "Configure Room" item - it's only logical :-)

**Comment by Ri0n** [comment]
fixed by 98b93a2eae0e0aa8e655a5eed137a7fb88cb8ed1 in upstream
