### ISSUE TITLE
Crash on tab opening with multi-row tabs (win64 msvc edition)

### ISSUE THREAD

**Issue by Vitozz** [psi-plus/main#706]
Steps to reproduce:
- launch psi+ for win64 (KukuRuzo)
- multi-row should be enabled
- open a few tabs (more than can fit in a row)
- crash

Backtrace:
https://pastebin.com/UicSv8y7

Tested with Psi+ v1.2.198 (2018-01-30, Psi:661eb20c, Psi+:825040f, webengine, sql)

Repeatability - 100%

**Comment by tehnick** [comment]
This bug in unreproducible in portable build (from tehnick).

**Comment by goriy** [comment]
The bug is still there in version:  
Psi+ v1.3.396 (2018-06-30, Psi:5ed84161, Psi+:ff32f79)

**Comment by Vitozz** [comment]
This bug exists only in 64bit version built with msvc. Try to use Tehnick's builds.

**Comment by Neustradamus** [comment]
Please note that there is no crash on x64 Windows KukuRuzo builds with:
- Options -> Messages -> Common -> "Use tabbed mode" disabled
- Options -> Plugins -> Extended Options Plugin -> Tabs -> "Enable multirow tabs" enabled

**Comment by Vitozz** [comment]
Fixed with https://github.com/psi-im/psi/commit/8c6524826061e1117eeec7e2a466ff40b7946be3
