### ISSUE TITLE
List of supported XEPs

### ISSUE THREAD

**Issue by elimohl** [psi-plus/main#707]
It would be nice to have a list of supported XEPs somewhere.
Something like
https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
https://github.com/dino/dino/wiki/Supported-XEPs

**Comment by Ri0n** [comment]
Definitely not full list but...
`grep -hoiP '(xep|jep)(-| )\d+' -r ./ | cut -d '-' -f 2 | sed 's/^0\+//' | sort -un`
4
22
25
27
33
47
50
59
60
65
66
70
71
78
79
85
86
91
115
144
146
153
166
167
172
184
231
232
280
297
308
316
363

**Comment by Vitozz** [comment]
Should we close this issue?

**Comment by Ri0n** [comment]
definitely. https://github.com/psi-im/psi/wiki/Supported-XEPs
