### ISSUE TITLE
Dependency problem libqt5keychain0 and libqt5keychain1

### ISSUE THREAD

**Issue by boospy** [psi-plus/main#709]
This time i would upgrade the system (KDE-NEON 16.04) i have an dependency problem. I'am not able to upgrade PSI+ because the whole nextcloudclient will be removed. PSI and Nextcloud are installed from the official repository. 

```
ppa:psi-plus/ppa
ppa:nextcloud-devs/client
```

Here are the apt information:
```
apt dist-upgrade                           
The following package has been automatically installed and is no longer needed:
  nextcloud-client-l10n
Use sudo apt autoremove to remove it.
The following packages will REMOVED:
  libnextcloudsync0 libqt5keychain0 nextcloud-client nextcloud-client-dolphin
The following NEW packages will be installed:
  libqt5keychain1
The following packages will be upgraded:
  psi-plus psi-plus-common psi-plus-plugins
3 updated, 1 reinstalled, 4 removed and 0 not updated.
```
Thanks very much vor help!
:)

**Comment by tehnick** [comment]
Show output of:
```
LC_ALL=C sudo apt-get dist-upgrade -V
```

**Comment by boospy** [comment]
```
LC_ALL=C  apt-get dist-upgrade -V 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
   nextcloud-client-l10n (2.3.3-20171224.060956~xenial1)
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
   libnextcloudsync0 (2.3.3-20171224.060956~xenial1)
   libqt5keychain0 (0.5.0-1build1~gcc5.1)
   nextcloud-client (2.3.3-20171224.060956~xenial1)
   nextcloud-client-dolphin (2.3.3-20171224.060956~xenial1)
The following NEW packages will be installed:
   libqt5keychain1 (0.7.0-3+16.04+xenial+build3)
The following packages will be upgraded:
   psi-plus (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
   psi-plus-common (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
   psi-plus-plugins (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
3 upgraded, 1 newly installed, 4 to remove and 0 not upgraded.
Need to get 4947 kB of archives.
After this operation, 4364 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.

```

**Comment by tehnick** [comment]
Eh! The quality of Ubuntu packages is terrible... =(
I will fix your problem soon.

**Comment by tehnick** [comment]
Just wait until [build](https://launchpad.net/~psi-plus/+archive/ubuntu/ppa/+sourcepub/8786211/+listing-archive-extra) is finished.

**Comment by boospy** [comment]
> Eh! The quality of Ubuntu packages is terrible... =(
Yes, i know... we have us own packagesrepository for a cuple of important packages...

> I will fix your problem soon.
Thanks a lot! You are the best!

**Comment by tehnick** [comment]
It should ready now.

**Comment by boospy** [comment]
Good morning. I've tryed it this day, but the problem exists. 

```
LC_ALL=C sudo apt-get dist-upgrade -V
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
   nextcloud-client-l10n (2.3.3-20171224.060956~xenial1)
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
   libnextcloudsync0 (2.3.3-20171224.060956~xenial1)
   libqt5keychain0 (0.5.0-1build1~gcc5.1)
   nextcloud-client (2.3.3-20171224.060956~xenial1)
The following NEW packages will be installed:
   libqt5keychain1 (0.7.0-3+16.04+xenial+build3)
The following packages will be upgraded:
   psi-plus (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
   psi-plus-common (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
   psi-plus-plugins (1.2.156-0ppa1~xenial1 => 1.2.215-0ppa1~xenial1)
3 upgraded, 1 newly installed, 3 to remove and 0 not upgraded.
Need to get 4947 kB of archives.
After this operation, 4261 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

Thanks

**Comment by Ri0n** [comment]
where does libqt5keychain0 come from? If kde neon is based on Ubuntu 16.04 then it should have just libqt5keychain1. So it's rather bug report for them.

**Comment by tehnick** [comment]
Hmm, I was a bit inattentive this night...
```
libqt5keychain1 (0.7.0-3+16.04+xenial+build3)
```
This version of library is not from our PPA. We use:
```
libqt5keychain1 (0.7.0-3ppa3~xenial1)
```
And after my changes this version of library will not conflict with libqt5keychain0 during installation.

Try something like:
```
sudo apt-get install -V libqt5keychain1=0.7.0-3ppa3~xenial1
sudo apt-get install -V psi-plus
```

**Comment by boospy** [comment]
Strange, with that it works. The problem seems to be from nextcloudppa. I've hold the libqt5keychain1 on this version. For the first an dist-upgrade is working fine now. I will do an bugreport nextcloud ppa. 
Very thanks for help here.

**Comment by tehnick** [comment]
> where does libqt5keychain0 come from?

@Ri0n Just look at: https://packages.ubuntu.com/search?keywords=qt5keychain

QtKeychain-0.5.0 is in Ubuntu Xenial (16.04 LTS). And is has very outdated API unsuitable for Psi+. That's why I use updated version of this library in our PPA.

Also see: https://launchpad.net/~psi-plus/+archive/ubuntu/ppa/+packages

**Comment by tehnick** [comment]
> Very thanks for help here.

Np. Also your report has allowed prevent of possible problems for other users.

**Comment by Ri0n** [comment]
oh yes. I checked on 17.10 instead. sorry for confusion.

**Comment by lapineige** [comment]
Hello,

In my case, with a nextcloud-client from the ppa, I have this issue:
> nextcloud: error while loading shared libraries: libqt5keychain.so.0: cannot open shared object file: No such file or directory

And that libqt5keychain.so.0 is not a valid package.
I only have libqt5keychain1.

But: 
> dpkg -S libqt5keychain1
libqt5keychain1:amd64: /usr/share/doc/libqt5keychain1/copyright
libqt5keychain1:amd64: /usr/share/doc/libqt5keychain1/changelog.Debian.gz
libqt5keychain1:amd64: /usr/share/doc/libqt5keychain1
libqt5keychain1:amd64: /usr/share/doc/libqt5keychain1/ReadMe.txt

Is that package valid ?
I don't see any binary here, and I can't even "fix" my issue with a symlink between libqt5keychain.so.0 and libqt5keychain1.

**Comment by tehnick** [comment]
> I can't even "fix" my issue with a symlink between libqt5keychain.so.0 and libqt5keychain1

Yes, you cannot. Because they have different ABI. Thats is why library version suffix was changed.

**Comment by lapineige** [comment]
What is an ABI ?

How it is supposed to work with v0 while only v1 is available ? I don't understand 😅

**Comment by tehnick** [comment]
@lapineige And here is bug tracker for Psi+, but not for Nextcloud. Ask for help to nextcloud maintainers who work with their PPA.

**Comment by tehnick** [comment]
> What is an ABI ?

https://en.wikipedia.org/wiki/Application_binary_interface

**Comment by tehnick** [comment]
> How it is supposed to work with v0 while only v1 is available ? I don't understand sweat_smile

Neither do I.

**Comment by lapineige** [comment]
Oh sorry, I thought it was related to Nextcloud. Thanks :)
