### ISSUE TITLE
[osx] Roster window minimises automatically after a while

### ISSUE THREAD

**Issue by woj-tek** [psi-plus/main#710]
Recently I've upgraded to `Psi+ v1.2.125 (2017-12-29, Psi:82a09527, Psi+:d27f6e7, webengine)` (from quite old `Psi+ v0.16.455 20150513`) and everything works just fine, except one thing - main roster windows minimises automatically after some time, which is a little bit annoying: you have open chat window + roster, you switch to another application and after a while you want to chat to someone so you switch back to Psi+, it shows only opened chats so you have to use spaces to open, now minimised, roster window to select the contact to chat.

**Comment by Ri0n** [comment]
Settings -> roster -> autohide

**Comment by woj-tek** [comment]
Oh my - I swear I wen't over the options multiple times yet I failed to see that. Thanks!

**Comment by Ri0n** [comment]
The problem was in changed logic of handling this option. Previously we had separate option just to enable/disable autohide.. I didn't write any migration code as far as I remember so it still affects some users. Sorry for that.

**Comment by woj-tek** [comment]
In the version `Psi+ v1.4.1303 (2020-05-27, Psi:f34443ba, Psi+:2170e90)` the problem started again. Mentioned option doesn't exist anymore, I find in advanced `options.contactlist.autohide-interval` and it was set to `600`.
