### ISSUE TITLE
Don't using stored password anymore

### ISSUE THREAD

**Issue by mowgli** [psi-plus/main#713]
I use psi+ of debian (1.2.248).

Recently it stopped logging in automatically. The password was still saved in ~/.config/psi+/profiles/default/accounts.xml but is now removed from it.

On the console I get the following messages:
```
[20180302 9:14:58] W:QFSFileEngine::open: No file name specified (unknown:0, unknown)
Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
[20180302 9:14:59] W:KeyChain error=5 (unknown:0, unknown)
[20180302 9:15:44] W:Failed to save password in keyring manager (unknown:0, unknown)
```

That looks for me that psi tries to connect some untrusted keyring software from gnome now. But I have no such gnome malware on my system I use fvwm desktop. For completness, I use pass password manager. I would never trust a password manager that is using dbus.

Is there any way to get back the behavior from earlier versions to store the password locally? It is pretty annoying to be asked for password with every start.

**Comment by Ri0n** [comment]
Yes you can disable keyring manager in the settings and keep using absolutely not secure internal password storage.

**Comment by mowgli** [comment]
Ah, thanks, I did not see such a setting before. Works for me.

The configuration is on a encrypted device and the password is soly used for jabber. So I am fine with the internal storage in psi.

**Comment by Vitozz** [comment]
Looks like the problem was solved.
