### ISSUE TITLE
[osx] psi+ crash macOS 10.13.3

### ISSUE THREAD

**Issue by Great2k** [psi-plus/main#714]
psi-plus-1.2.125-qt5-webengine-git-2017-12-29-macosx.dmg

crash the start

Psi+ падает сразу при запуске, стабильно, удаление файлов от предыдущей сборки не помогло!

[crash_psi+.txt](https://github.com/psi-plus/main/files/1814435/crash_psi.txt)

**Comment by Vitozz** [comment]
Any news? Should we close this issue?

**Comment by tehnick** [comment]
С теми сборками были проблемы. Мои сборки не падают. Поддержка macOS 10.13 пока есть. Можно закрывать.
