### ISSUE TITLE
Forms with text-multi are not displayed

### ISSUE THREAD

**Issue by woj-tek** [psi-plus/main#716]
I've been running into an issue with execution of ad-hoc commands (via Service Discovery) - in the version `Psi+ v1.2.125 (2017-12-29, Psi:82a09527, Psi+:d27f6e7, webengine)` some forms are not displayed. IQ is received correctly  but there is now GUI. So far the only difference I've noticed was that problematic IQs contain multi-line fields:

    <field type="text-multi" var="…

Has anyone run into same problem?

**Comment by Ri0n** [comment]
Never hears about such a problem. From what I can see in the code text-multi is handled the same way as all others field types.
Is there a way to test it?

**Comment by woj-tek** [comment]
You can try on tigase.im/sure.im - in service discovery VHost manager -> add new item. There is a first form where you can add your domain/VHost and after filling it out you should receive confirmation (this is just an example, it happens with different commands as well). I just noticed that this particular response doesn't have 'text-multi' field, so I'm leaning more towards "second form of any ad-hoc is not shown.

**Comment by woj-tek** [comment]
It looks ok now.
