### ISSUE TITLE
Incoming chats are not always received

### ISSUE THREAD

**Issue by klou** [psi-plus/main#717]
1.3.306_win7_x86_64, tehnick's build.

Run in "non-portable mode"

Sometimes I won't receive incoming messages, which are then delivered upon the next log in.  

How can I go about troubleshooting this?

**Comment by Ri0n** [comment]
Hm looks like are silently loosing connection. Could you describe in more details when and how this sometimes happen?

**Comment by klou** [comment]
Honestly, I don't have an idea, nor can I accurately replicate this.  I'm trialing the recent builds, but the rest of my users are on 0.16.469-webkit-64 (2015-08-13).  They don't have this problem, but I've noticed it off and on up to the 1.3.306 (webkit).

Usage is mostly single user chats, the occasional group message (not MUC), and occasional file transfer (using my openfire server as a data transfer proxy).  

Account -> Connection -> Send "Keep-alive" packets are enabled, though I'm not actively monitoring them.

**Comment by tehnick** [comment]
You may try to disable the Stream Management in Connection tab of Account Properties.

**Comment by klou** [comment]
This same issue was observed with OSX 1.2.105 (2017-10-28).

@tehnick We've made the suggested changes on both the OSX and 1.3.306.  I'll let it run for a while and keep an eye on it.

**Comment by Neustradamus** [comment]
Have you tried with the last Psi+ build?

**Comment by klou** [comment]
So far, tehnick's 1.3.360 x64 build seems to be behaving properly, with Stream Management being enabled.  

The OSX 1.2.105 also behave better, but with Stream Management disabled.

**Comment by klou** [comment]
Recurrence of issue with 1.3.370, Stream Management enabled.  So the above result (1.3.360) might be false.

**Comment by Neustradamus** [comment]
@klou: Have you tested with new builds?

**Comment by klou** [comment]
Partially -- I haven't spent a huge amount of time with them but they're more stable in regards to "not receiving messages (1.4 branch).  However, I'm still disabling Stream Management both at the client and also at the server level (via Openfire's stream.management.active=false).  Should I test combinations?

I'm also currently deploying Psi (not psi-plus) 1.4 to OSX, with the above settings and good results.

**Comment by klou** [comment]
Tested with 1.4.675 x64 Windows (non webkit), Openfire stream.management.active=false, PSI+ Account Properties->Connections->Enable Stream Management=TRUE.

Still occasionally not receiving direct chat messages, though they pop up immediately after a logout/logon.

**Comment by Vitozz** [comment]
Any news? Should we close this issue?

**Comment by Neustradamus** [comment]
Normally, this problem will be fixed when the support of XEP-0410: MUC Self-Ping (Schrödinger's Chat) will be done:
- https://github.com/psi-im/psi/issues/670
- https://github.com/psi-im/psi/issues/758

**Comment by Ri0n** [comment]
Nobody else reported this for years. I guess it's fixed. In any case without xml logs it's hard to say. Closing
