### ISSUE TITLE
[PluginRequests] TOX 

### ISSUE THREAD

**Issue by Cybermaxrus** [psi-plus/main#719]
Greetings!
Please make [TOX](https://en.wikipedia.org/wiki/Tox_%28protocol%29) plug-in for PSI+, if possible. I think this is an interesting protocol.
Thanks!

**Comment by kirillsurkov** [comment]
It will be very nice plugin

**Comment by rapgro** [comment]
IMHO better look for a so called gateway to transfer between XMPP/Jabber and TOX.

**Comment by rapgro** [comment]
Maybe toxcore can be used:
https://github.com/TokTok/c-toxcore

**Comment by tehnick** [comment]
Psi+ is not multi-protocol software.

**Comment by Cybermaxrus** [comment]
I thought so...

**Comment by rapgro** [comment]
Without the want to do some anti advertisement, maybe take a look for an alternative client:
https://tox.chat/clients.html
