### ISSUE TITLE
Problem for mucroom admin on russian XMPP servers, Russian lang (instead English)

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#720]
There is a problem for mucroom admin on russian XMPP servers (tested on jabber.ru and xmpp.ru), it is in Russian (instead English):
- https://image.ibb.co/g2xKmc/psi_plus_jabber_ru_mucroom_admin.png

**Comment by Neustradamus** [comment]
It is a problem with the jabber.org XMPP Isode M-Link server.

**Comment by Neustradamus** [comment]
@rion, @tehnick, @Vitozz: Currently, it is always same:
- In Russian with Psi+
- In English with Psi

A fix soon?

**Comment by Ri0n** [comment]
check xml console if english variant ever exists

**Comment by Vitozz** [comment]
I think we should close this ticket.

**Comment by Ri0n** [comment]
let's close. no feedback and looks to be a server problem
