### ISSUE TITLE
Bad icons of the client (Psi instead of Psi+)

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#721]
Not the good icon for:
- "Show information about plugin" window
- "Application" in Options window
- "Psi - The main Psi button, that provides access to many actions" in Toolbar buttons options
- "About" in Toolbar buttons options

Note that "Psi - The main Psi button, that provides access to many actions" is not good too

In the same time, about current logo, it is the old Psi+ logo, not the new.

**Comment by tehnick** [comment]
Fixed.
