### ISSUE TITLE
FR: X-obb tag

### ISSUE THREAD

**Issue by gerroon** [psi-plus/main#723]
Hi

This is based ona bug I opened with Conversation team. Basically uploads are not "uploaaded" to mesages properly. 

FR: Parse image urls as inline images 
See  @iNPUTmice's reply/
 
https://github.com/siacs/Conversations/issues/3049

**Comment by dos1** [comment]
https://github.com/psi-im/plugins/commit/70ce2db01d06629c5753a920dfd813c5fd42921b ?

**Comment by dos1** [comment]
So update it - it's already fixed since April 8.

**Comment by gerroon** [comment]
@dos1 

Thanks I am using it on Debian Testing. I will wait until a new release. 

Thanks for the fix.

**Comment by gerroon** [comment]
@dos1 

In which version is this fixed? I installed 1.3.355 and still not working


thanks

**Comment by gerroon** [comment]
Ok I was mistaken, it works only one way meaning that uploads from Psi+ to Conversations work but from Conversation to Psi+ uploads looks like  plaintext in this format in the message window

```  aesgcm://MYDOMIAN.com:PORT/upload/5ac7d44f1c8628be13ee801828a7b6adceeb03f4/PhOQ7BuFI0gfRNU9kmHbEVvZPcx89xLi3vmoSp6o```

**Comment by dos1** [comment]
That's a completely different, unrelated issue: `aesgcm://` URIs are for files encrypted with OMEMO. Make sure you have your OMEMO plugin enabled and up-to-date.

**Comment by gerroon** [comment]
@dos1 

Thanks for the info. Are these uploads from Psi+ encrypted (with omemo, assuming clients accept eachother) as well like Conversation does?

**Comment by dos1** [comment]
From a quick glance to the code, I don't think so.

**Comment by gerroon** [comment]
@dos1 thanks for the follow up. 

Shall I open a request ticket?

**Comment by Neustradamus** [comment]
@gerroon: Any news about it?
