### ISSUE TITLE
System tray icon does not notify about unread messages under some circumstances.

### ISSUE THREAD

**Issue by Aqa-Ib** [psi-plus/main#726]
Steps to reproduce the issue:
1. Go to Options → Messages and select "Use tabbed mode: for mucs, chats and roster in one window".
2. Go to Options → Misc. and select "Treat incoming messages: Messages".
3. Open a conversation with a contact.
4. Close Psi+ window (it remains running in the background with the system tray icon being available).
5. Now, if the contact that you opened a conversation with sends you a message, the system tray icon won't notify you about it.

Thanks for you attention.

**Comment by Aqa-Ib** [comment]
I already have that option set in with "no animation". I use Plasma Desktop 5.12.5.

Thanks for you attention.

**Comment by Vitozz** [comment]
Not reproducible. I'm using Plasma  5.17.5 and do not have such problem.

**Comment by Neustradamus** [comment]
@Aqa-Ib: Have you same problem with latest Psi+ build?

**Comment by Aqa-Ib** [comment]
Unfortunately, I do not use Jabber these days. I do not have accounts to test this. I guess I can close this issue. Thanks for your attention.
