### ISSUE TITLE
Empty space in Status button

### ISSUE THREAD

**Issue by Katarn** [psi-plus/main#730]
At left side:

![default](https://user-images.githubusercontent.com/6339978/42137117-8027322c-7d6f-11e8-8f18-26c17fb5226e.png)

In Psi 0.14 the text and icon aligned on the left side.

**Comment by Ri0n** [comment]
Psi 0.14 is not supported anymore. What exactly do you want?

**Comment by Katarn** [comment]
Align the icon and text to the left side. The down arrow on the right side here prevents intuitively understanding that the icon and text are centered on the button.

**Comment by Vitozz** [comment]
This will not be fixed.
