### ISSUE TITLE
Как в PSI настроить свой псевдоним ддля отображения у собеседников? 

### ISSUE THREAD

**Issue by 0lolosh** [psi-plus/main#733]
Например, если я использую длинный и уродливый JID вида 436е4363437@jabber.ru, то мне почему-то противно смотреть на такие цифры в окне переписки и они путаницу некоторую вызывают кто это писал вообще. Может можно как-то ник свой ещё задать? Не в конфах, а именно для отображения в переписке с собеседниками из ростера.

**Comment by tehnick** [comment]
В ростере: правый клик на контакте --> Переименовать. Или по F2.
