### ISSUE TITLE
psimedia patch with cmake

### ISSUE THREAD

**Issue by rapgro** [psi-plus/main#734]
psimedia patch does not work with cmake and is useless because no modification to CMakeLists.txt like for qmake files

**Comment by Vitozz** [comment]
Why did you open this ticket? This patch should not work with cmake. And also this patch is in dev folder and all patches from this folder are not stable and only for developers

**Comment by tehnick** [comment]
@rapgro It looks that you have misunderstood the purpose of this patch. It you are interested in psimedia plugin, look at its git repo: https://github.com/psi-im/psimedia No changes in it are required. But it works only GNU/Linux systems for now...

**Comment by rapgro** [comment]
Old package in Fedora have had this patch applied. We switched to cmake.

**Comment by tehnick** [comment]
> We switched to cmake.

And psimedia from master branch may be easily compiled using cmake.
