### ISSUE TITLE
Different presence status in contact window/tab, contact in mucroom window/tab and main roster

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#740]
Different presence status in contact window/tab, contact in mucroom window/tab and main roster.

The same contact is in main roster, in mucroom etc.

Examples:
- Offline in contact window/tab and online in roster
- Online in contact window/tab and dnd in roster
- Online in mucroom window/tab and dnd in roster
- ...

Please note that I am not sure if same for Psi because I use Psi+.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/psi-plus/main/issues/744

**Comment by Vitozz** [comment]
I think we should close this ticket

**Comment by Ri0n** [comment]
yep. I tried to reproduce it recently but it worked fine for me.

**Comment by Neustradamus** [comment]
No it is not solved, always here.

**Comment by Neustradamus** [comment]
No it is not solved, always here.
- https://i.ibb.co/230yDnT/psi-plus-status-vcard-muc-roster.png

Like I have already informed Psi team and directly tested few days ago with the team leader named "@Ri0n".

Open the vCard of an user in MUC Room and the vCard of the same user in your Roster
Go to Status tabs and do not close it

Now ask to your contact to change the status (for example: Online to Away/DND/F2C/XA).

You can see:
- The change in vCard Status tab from Roster contact (perfect)
- No change in vCard Status tab from MUC Room user (problem)

Do not close it,

Now look the tooltip:
- From Roster contact: No problem in tooltip
- From MUC Room: No problem in tooltip

The problem is only in vCard Status Tab of the user in MUC Room.
