### ISSUE TITLE
[Multirows] In multiline mode, when you try to pin the active tab, a completely different tab is pinned

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#741]
When there is more one line of tabs, when we try to pin the active tab, it is not the active tab which is pinned.
If we pin a tab which is not active (only right click on the tab and "Pin Tab"), no problem.
If only one line of tabs, no problem for pin active tab.
No problem for "Unpin Tab".

The problem exists only if more 1 line of tabs.

**Comment by Vitozz** [comment]
Fixed with https://github.com/psi-im/psi/commit/36e4e6c51e7199cd1ee1d2353e184aaeb5172751

**Comment by Neustradamus** [comment]
Thanks @Vitozz for your solution!

But now, the pinned tab size is limited to 6 letters :/

**Comment by Neustradamus** [comment]
@ri0n: I think, it can be moved to @psi-im/psi.
Thanks in advance.
