### ISSUE TITLE
Text copying stops working

### ISSUE THREAD

**Issue by DaarkWel** [psi-plus/main#742]
Text copying in chat window and in roster too stops working after some time. Not CTRL-C, not right mouse menu «Copy» doesn't work until restart Psi+. In terminal there's this message: W:QXcbClipboard::setMimeData: Cannot set X11 selection owner (unknown:0, unknown).

Linux x64
Psi+ v1.4.460 (2018-12-12, Psi:9803b48e, Psi+:2c6f671)
Qt version 5.12.0.

**Comment by DaarkWel** [comment]
I don't have separate qtgui package in my archlinux. qt5-base has updated from 5.11 when I first time did notice this bug to 5.12. I tried to rebuild psi+ itself several times with no luck :-(

**Comment by beelze** [comment]
can you revert qt то 5.11 and check for this issue?

**Comment by DaarkWel** [comment]
Sorry for my vague comment. I was on 5.11 when I first saw this issue.

**Comment by DaarkWel** [comment]
Several months and several versions later, the problem still persist.

**Comment by tehnick** [comment]
Try another Qt Theme.

**Comment by DaarkWel** [comment]
Ok, I will. But why?

**Comment by beelze** [comment]
Setting another theme/style didn't help as I stated before. At least `-style windows`. I've tried `gtk+` and `adwaita` too but it's the same. Relevant message is:
```
W:QXcbClipboard::setMimeData: Cannot set X11 selection owner (unknown:0, unknown)
```

**Comment by DaarkWel** [comment]
Yep, it didn't help. Same message.

**Comment by tehnick** [comment]
>> Try another Qt Theme.
>
> Ok, I will. But why?

We had discussed the same bug report in our developers groupchat few months ago. Unfortunately, I do not remember what is helped user finally. But I remember that we discussed a lot about Qt styles.

Probably you know, what unlike GTK+ 3.x themes, which may change only look and feel of UI via CSS and such like, Qt themes (styles) may significantly change behaviour of Qt widgets. And this is especially important in GTK+ based DE, where where is no standard way in Qt application to mimic to GTK+ ones after switching to GTK+ 3.x.. (You may google about `gtkplatform`, `gtk-qt-engine`, `qgtkstyle`, `QGnomePlatform`, `Qt5Gtk2`, etc..)

That is it why the Qt theme is the first thing which come to mind when I read such bug reports.

**Comment by tehnick** [comment]
BTW, which DE do you use? Is it launched above X11 or Wayland? Which input library do you use?

**Comment by tehnick** [comment]
> Which input library do you use?

As far as I see, you use Arch Linux and I suppose that it switched to `libinput` long time ago. Which version of `libinput` is installed in your system now?

**Comment by beelze** [comment]
After some thorough testing, neither `evdev/libinput` switching nor using different Qt styles didn't help. Sometimes copying stops almost immediately, sometimes after a whole day, but in the end the result **always** the same. Other Qt programs affected too, including `qpfdview`.

Another thing I noticed that `W:QXcbClipboard::setMimeData` error appeared not only when **copying** text but even on **selecting** it. Why? Can we turn off copying-on-select or whatever it called?

```W:QObject::startTimer: Timers cannot have negative intervals (unknown:0, unknown)```
almost always appears around `setMimeData` error. It may be revevant.

**Comment by DaarkWel** [comment]
> BTW, which DE do you use?

It's just WM Openbox above X11.

> Which version of `libinput` is installed in your system now?

It was about 1.12.4 when I first noticed this issue and it's 1.13.1 now.

> Sometimes copying stops almost immediately, sometimes after a whole day, but in the end the result **always** the same.

Same here.

> Other Qt programs affected too, including `qpfdview`.

Yes, I noticed it just yesterday, in my case it was `GoldenDict`.

> W:QObject::startTimer: Timers cannot have negative intervals (unknown:0, unknown)

I didn't see that error.

**Comment by Vitozz** [comment]
Any news? Should we close this issue?

**Comment by DaarkWel** [comment]
> Any news? Should we close this issue?

I guess it's basic QT issue for it affects not only psi-plus but other QT apps, in my case Telegram-desktop and goldendict. It still persist and it's freakin' annoying. But you can close this issue here, I think. Thanks for trying.
