### ISSUE TITLE
[Multirows] Pinned tabs do not wrap to the next line in multiline mode

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#743]
A pinned tab in the first line is not complete, next completely hidden, the next in the second line....
- https://i.ibb.co/7XzCK12/psi-plus-multirows-bug.png

**Comment by Vitozz** [comment]
This is not a bug, this behavior was intended by the developer. But I think it can be corrected by making all the text visible.

**Comment by Vitozz** [comment]
As I see bug was fixed. Please check and close the issue

**Comment by Neustradamus** [comment]
Yes the problem has been fixed with the first ticket.
-> https://github.com/psi-plus/main/issues/741

**Comment by Neustradamus** [comment]
@ri0n: I think, it can be moved to @psi-im/psi.
Thanks in advance.
