### ISSUE TITLE
jabber connection lost

### ISSUE THREAD

**Issue by madmanidze** [psi-plus/main#745]
Lost connection to jabber server (openfire), but client show account online.

**Comment by Ri0n** [comment]
what exactly do you mean by lost?
what version of Psi are you using?
Anything unusual in Psi's xml log?

**Comment by Ri0n** [comment]
Can you reproduce it every time?
Do you have an account to test?

**Comment by madmanidze** [comment]
Psi+ v1.4.532

where i can find xml log?

**Comment by Ri0n** [comment]
in context menu of account in contacts list

**Comment by madmanidze** [comment]
psi starting fine, connect to jabber, then after some time - close group chat on this server and on server side client show offline.

**Comment by madmanidze** [comment]
ok, trying to collect logs.

**Comment by madmanidze** [comment]
`<presence to="john@jabber-server.com/Psi+" type="unavailable" from="john@jabber-server.com/Psi+"/>

<presence to="john@jabber-server.com/Psi+" type="unavailable" from="conf@conference.jabber-server.com/john">
<show>xa</show>
<priority>30</priority>
<c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://psi-plus.com" ver="/048CkZCf5htI1869kIc1lkveJg="/>

<x xmlns="vcard-temp:x:update">
<photo>217b035871f10ef7b78e4666daaf5dba98d917df</photo>
</x>
<x xmlns="http://jabber.org/protocol/muc#user">
<item jid="john@jabber-server.com/Psi+" role="none" affiliation="owner"/>
<status code="110"/>
</x>
</presence>`

**Comment by madmanidze** [comment]
`
<presence to="john@jabber-server.com/Psi+" type="unavailable" from="john@jabber-server.com/Psi+"/>

<presence to="john@jabber-server.com/Psi+" type="unavailable" from="conf@conference.jabber-server.com/john">
<show>xa</show>
<priority>30</priority>
<c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="http://psi-plus.com" ver="/048CkZCf5htI1869kIc1lkveJg="/>

<x xmlns="vcard-temp:x:update">
<photo>217b035871f10ef7b78e4666daaf5dba98d917df</photo>
</x>
<x xmlns="http://jabber.org/protocol/muc#user">
<item jid="john@jabber-server.com/Psi+" role="none" affiliation="owner"/>
<status code="110"/>
</x>
</presence>
`

**Comment by madmanidze** [comment]
https://pastebin.com/9pYMCT5v

**Comment by Ri0n** [comment]
and of course closing a groupchat shouldn't affect client's status on server side. looks really like an openfire bug.

**Comment by madmanidze** [comment]
But all working fine on Ubuntu Xenial with 0.16.330 version. After upgrade to bionic and install psi-plus from ppa - got that bug...

**Comment by Ri0n** [comment]
since then stream management was integrated. you can try to disable it in account settings

**Comment by madmanidze** [comment]
that helped, thank you.

**Comment by Vitozz** [comment]
Look like problem resolved,
