### ISSUE TITLE
Where i can activate Omemo?

### ISSUE THREAD

**Issue by boospy** [psi-plus/main#746]
I installed the newest Version from here: https://launchpad.net/~psi-plus/+archive/ubuntu/ppa?field.series_filter=bionic  I activated the plugin and generate key. But can't find an omemo button. 

I'am able to get omemo messages, but if i send back i will be only gpg. Can anyone help me?

KDE Neon 18.04 with PSI+ v1.4.554

**Comment by tehnick** [comment]
1) Enable OMEMO plugin.
2) Add OMEMO button to chat and groupchat toolbars in Psi+ Options dialog.
3) Disable GnuPG plugin. And if it will not help then:
```
sudo rm /usr/lib/psi-plus/plugins/libgnupgplugin.so
```

**Comment by Neustradamus** [comment]
@boospy: Maybe you can update your Psi+ XMPP Client?

There are a lot of OMEMO improvements.
