### ISSUE TITLE
[OTR plugin] Необработанное исключение по адресу 0x000000000C11F44E (libgcrypt-20.dll)

### ISSUE THREAD

**Issue by mekuto** [psi-plus/main#750]
Arch: x86_64
WIndows 8 x64
Psi+ v1.4.554 (2019-02-08, Psi:94590587, Psi+:7d675e3)
Plugin: Off-the-Record Messaging Plugin

Выпадение при попытке генерации ключа для собственного хоста (идентификатора).

Необработанное исключение по адресу 0x000000000C11F44E (libgcrypt-20.dll) в psi-plus-webkit-portable.exe: 0xC0000005: нарушение прав доступа при чтении по адресу 0x0000000000001FC3.

**Comment by Vitozz** [comment]
Проблема известная, связана со сторонними библиотеками libotr и libgcrypt. Попробуйте 32х битную версию Пси+.

**Comment by tehnick** [comment]
https://github.com/psi-im/plugins/issues/45

**Comment by tehnick** [comment]
@mekuto Если регулярно используете OTR плагин в MS Windows, используйте 32-битную сборку программы.

**Comment by claucece** [comment]
проверьте обходной путь, предложенный @tehnick здесь: psi-im/plugins#45

**Comment by tehnick** [comment]
Исправлено в `psi-plus-portable-1.4.574_win7_x86_64.7z`
