### ISSUE TITLE
[Multirows] Add an option to not move the tab at first row when we select a tab

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#754]
Add an option to not move the tab at first row when we select a tab, keep the same place

**Comment by Vitozz** [comment]
There is an option for this options.ui.tabs.current-index-at-bottom

**Comment by Neustradamus** [comment]
It is in Psi Options or in Extended Options plugin?

**Comment by Vitozz** [comment]
Option already exists!

**Comment by Neustradamus** [comment]
@Vitozz: Thanks for your commits from today!

**Comment by Neustradamus** [comment]
@ri0n: I think, it can be moved to @psi-im/psi.
Thanks in advance.
