### ISSUE TITLE
не работает запоминание паролей

### ISSUE THREAD

**Issue by m-jackson** [psi-plus/main#755]
не работает запоминание паролей от акаунтов в пси+ каждый раз при рекноектах приходится вводить снова.
psi-plus --v
ePsi+ 1.4.509 (2018-12-28, Psi:890dc0c6, Psi+:d75b610)
Qt 5.9.5
Compiled with Qt 5.9.5

ос - linux ubuntu 18.04
![screenshot from 2019-03-05 12-14-47](https://user-images.githubusercontent.com/7161238/53794250-ab8b4a00-3f40-11e9-99d8-e96bb401f584.png)
![screenshot from 2019-03-05 12-14-02](https://user-images.githubusercontent.com/7161238/53794251-ac23e080-3f40-11e9-8242-c53e17efdd24.png)

**Comment by tehnick** [comment]
Установите libgnome-keyring0 **или** отключите в диалоге настройек Psi+ опцию "Использовать системный менеджер паролей".

**Comment by m-jackson** [comment]
спасибо, помогло
