### ISSUE TITLE
[Website] Bad links and bad parts

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#756]
On https://psi-plus.com/
- xmpp:psi-dev@conference.jabber.ru?join does not work
- Ohloh has been replaced Open Hub by https://www.openhub.net/p/psi-plus
- Forums is dead, must to be removed, update links and http/https redirected to https://groups.google.com/group/psi-users.
- It is better to have only one wiki, because plugins are now in the main code: https://github.com/psi-im/psi/wiki

**Comment by Vitozz** [comment]
About the wiki absolutely disagree. the psi + project has its own wiki, which has nothing to do with the psi project.

**Comment by tehnick** [comment]
`+1` for  @Vitozz note about Psi+ wiki. I'll fix other points a bit later.

**Comment by tehnick** [comment]
@Neustradamus 
BWT, I propose you to prepare next issues using task lists instead of plain lists. Example:
- [x] Item 1
- [ ] Item 2
- [ ] Item 3

**Comment by Neustradamus** [comment]
About the wiki, plugins are in Psi.

**Comment by tehnick** [comment]
Psi+ wiki is not only about plugins. Plugins related pages may be moved to Psi wiki.

**Comment by tehnick** [comment]
1. Done.
2. Done.
3. Done.
4. Will not be done.

Also other changes at main page and clean up at website were done.

**Comment by Neustradamus** [comment]
Plugins can be move:
-> It is in Psi code!
