### ISSUE TITLE
Не подключается по имени хоста

### ISSUE THREAD

**Issue by tonal** [psi-plus/main#757]
ОС: KDE neon User Edition 5.15 amd64 (based ubuntu 18.04) + all updates
Версия Psi+ v1.4.592 (2019-03-11, Psi:93000d8c, Psi+:50584c5) из ppa

Причём февральская сборка нормально работала.

Лечится указанием IP вместо имени хоста.

**Comment by Ri0n** [comment]
если обратно поставить февральсую сборку то работает?

**Comment by Ri0n** [comment]
@tehnick у нас jdns там нигде случайно сам не включился?

**Comment by tehnick** [comment]
@Ri0n Судя по логам сборки -- нет. Если нужно самому выяснить, грепай по слову `USE_QJDNS`. При включении этой опции будет предупреждение вида:
```
CMake Warning at iris/CMakeLists.txt:42 (message):
  USE_QJDNS flag is enabled with Qt5.  If you have problems with connection
  please disable this flag
```

**Comment by tonal** [comment]
Обратно ставить сборку - не пробовал. У коллеги на стоит - работает.
С моей подключается к jabber.ru без проблем.
Ну и про dig отписал в конфе: https://groups.google.com/d/msg/psi-users/zKXP0xEZtlw/yJzQtVAxBgAJ

**Comment by tehnick** [comment]
> Ну и про dig отписал в конфе: https://groups.google.com/d/msg/psi-users/zKXP0xEZtlw/yJzQtVAxBgAJ

Не вижу смысла дублировать сообщения. Продолжим обсуждение в списке рассылки. Ссылка на нить обсуждения в этом issue уже есть, кому будет нужно, перейдут по ней.
