### ISSUE TITLE
Нет соединения с сервером при включенных настройках proxy в IE

### ISSUE THREAD

**Issue by zxaksh** [psi-plus/main#758]
Добрый вечер
PSI+ не соединяется с сервером (ejabberd) если в настройках браузера IE в Windows 10 на компьютере пользователя включен proxy-server.
Если настройку proxy в IE отключить, то соединение с сервером проходит без проблем и все работает отлично. Проверял на последней и предпоследней сборке для windows x64. 
Проверял также Pidgin, ни каких проблем в работе при включённом IE proxy у него нет.
В чем может быть проблема?

**Comment by Ri0n** [comment]
Думаю сетевая подсистема Qt пытается сделать HTTP CONNECT, который часто бывает закрыт на всех портах кроме 443

**Comment by tehnick** [comment]
@zxaksh Попробуйте сборку для WinXP.

**Comment by zxaksh** [comment]
Да, все верно, у сборки для XP таких проблем нет, все работает, спасибо.
Но надеюсь когда-нибудь будет исправлена и x64 версия.

**Comment by tehnick** [comment]
Там разница в версиях Qt и резолвере DNS: для WinXP используется наш старый костыльный резолвер, а для Win7 и новее -- встроенная реализация из Qt 5.x.

**Comment by tehnick** [comment]
> Но надеюсь когда-нибудь будет исправлена и x64 версия.

Ее можно использовать хоть сейчас. Просто в настройках аккаунта на вкладке "Соединение" нужно будет IP адрес сервера вручную прописать.

**Comment by zxaksh** [comment]
Проверил работу x64 сборки с указанием прямого IP в настройке аккаунта (как было сказано выше) - не работает!

**Comment by tehnick** [comment]
Это странно. Должно было сработать. Других идей пока нет.

**Comment by liuch** [comment]
Я бы еще проверил доступ к этому IP-адресу от вашего компа, на всякий случай, вдруг эти два резолвера дают разные IP-адреса.

**Comment by tehnick** [comment]
Я тут на баг-репорт по другой проблеме наткнулся:
https://bugreports.qt.io/browse/QTBUG-61692
Но это навело на мысль, что возможно нам нужно где-то в коде явным образом использование системного прокси отключать.

**Comment by Ri0n** [comment]
Я пока захардкодил НЕиспользование системных проксей.
