### ISSUE TITLE
it'd be nice if we were able to post anonymously. 

### ISSUE THREAD

**Issue by anontests** [psi-plus/main#759]
it'd be nice if we were able to post anonymously. 

by that i mean posting on this github thing anonymously. 

i'm not sure if that's possible. but it'd be nice. 

'cause i sorta wanna have it focus on the topic; without being tied to me by a username or whatever. 

by the way. also this is sort of a "feature" request. not sure how to add "labels" on here. 

by the way. it'd be nice if there wasn't an "edit history". i understand the purpose of it. but. eh. too meta for me. cure is worse than the sickness. anyway. 

just putting it out there. 

thanks

**Comment by Ri0n** [comment]
If you want to just ask a question, join our conference psi-dev@conference.jabber.ru
github won't allow to post anonymously

**Comment by tehnick** [comment]
> github won't allow to post anonymously

WTF!? Why not? **Any** Internet user may register GitHub account to **any** email and write **any** information in account settings.
