### ISSUE TITLE
it'd be nice if psi-plus was more avatar-oriented ailke gajim andor have avatars show-up in channels or chat-rooms or whatever. by default. 

### ISSUE THREAD

**Issue by anontests** [psi-plus/main#760]
it'd be nice if psi-plus was more avatar-oriented ailke gajim andor have avatars show-up in channels or chat-rooms or whatever. by default. 

stuff you don't gotta read: 

if everyone hates avatars then i don't mind if avatars is the "mainstream" version default and then having a "minimal" version as an option; for those that care about it so much. i don't know. so. 

i didn't really test psi-im or psi-plus too much. 

but gajim is really avatar-oriented. avatars appear everywhere. by default. the user-list, the chat room channels, and stuff. by default. 

i really like gajim because it has avatars in chat-rooms and everywhere and stuff. 

but gajim is sorta broken and even the dev team doesn't know what to do sometimes and just sorta ignores me. apparently. . by the way. hence why i'd want to be able to post anonymously; so at least it's not the name that has to be ignored; but the issue that has to be ignored; haha. 

so if psi-im or psi-plus had avatars everywhere in chat-rooms or whatever then that'd be the ultimate. 

discordapp is trash. skype etc. says you need ac ell phone number and tracks you and stuff. irc mods can ban you. it's a pain. there's also the idea of using e-mail as a sorta instant-messenger. but it's not really an instant-messenger. nor is it designed to be. so. the idea of using e-mail as an instant-messenger. that remains to be seen. anyway. 

i really want jabber xmpp to be mainstream. i loved instant messengers in the past. but everything became so bad. jabber-xmpp would be really good in the immediate present. 

too long; didn't read: 

it'd be nice if psi-plus was more avatar-oriented ailke gajim andor have avatars show-up in channels or chat-rooms or whatever. by default. 

please help me. 

anyway. 

i hope this helps. 

take care.

**Comment by Ri0n** [comment]
avatars are enabled everywhere by default  already. wait for the next version if in the current one they aren't
