### ISSUE TITLE
Harmonization of the Psi+ logo

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#762]
It is possible to have the same Psi+ logo everywhere?
Good is on already here: https://www.facebook.com/psiplus/photos/
- Client (Linked to https://github.com/psi-plus/main/issues/721)
- MUC Room logo (xmpp:psi-dev@conference.jabber.ru)
- Github (https://github.com/psi-plus)
- Website (https://psi-plus.com/)
- OpenHub (https://www.openhub.net/p/psi-plus)
- ...

Examples:
- https://psi-plus.com/favicon.ico
- https://psi-plus.com/logo_site_flat.png
- https://psi-plus.com/img/psiplus.png
- https://psi-plus.com/wiki/_media/logo_wiki.png

Note: Facebook and VK are already good.

**Comment by Neustradamus** [comment]
Any news in 2020?

**Comment by tehnick** [comment]
Why not [original](https://github.com/psi-plus/main/blob/master/iconsets/system/default/psiplus/logo_128.png) logo?

**Comment by tehnick** [comment]
Any opinions?

**Comment by Neustradamus** [comment]
@tehnick: No, the good logo is already on VK and Facebook.

**Comment by tehnick** [comment]
Done.

**Comment by Neustradamus** [comment]
@tehnick: Thanks but it is not complete yet ^^
- https://github.com/psi-plus/

In the same time on OpenHub (https://www.openhub.net/p/psi-plus):
1/ Can you update:
Psi is a cross-platform powerful XMPP client (Qt, C++) designed for the Jabber power users.
->
Psi is a cross-platform powerful XMPP client (Qt, C++) designed for the XMPP power users.

Psi+ Groupchat: psi-dev@conference.jabber.ru
->
Psi+ Groupchat: xmpp:psi-dev@conference.jabber.ru?join

More information, http://psi-plus.com/
->
More information, httpS://psi-plus.com/

Can you update links:
- httpS://psi-plus.com/
- httpS://psi-plus.com/wiki/
- httpS://forum.psi-plus.com/
- httpS://psi-plus.com/

I have forgotten the forum:
- https://forum.psi-plus.com/styles/prosilver/imageset/logo_site_flat_forum.png

**Comment by tehnick** [comment]
All is done.
