### ISSUE TITLE
"Share Files" via HTTPUpload mangles filenames with spaces

### ISSUE THREAD

**Issue by klou** [psi-plus/main#765]
This may be more of an HTTPUpload issue (I use Openfire), but it slightly mangles the filename when pushed to HTTPUPload via File Share, IF the file name has white spaces in it.

As a result, the link presented to the chat window is ```"http://<server>/httpfileupload/<uuid>/<firsthalffilename>" <nameafterspace>```, with only the quoted portion acting as a URL (which also matches the file that has been uploaded).  

I realize that HTTP and filename-spaces don't mix will -- but perhaps it's better to substitute %20 for the white space before push, but it also might be server-side.

**Comment by Ri0n** [comment]
it definitely not a Psi issue. Psi provides valid full name with spaces to the server, and it's server that returns the urls for upload and download.
