### ISSUE TITLE
Не выходить из конференции при закрытии окна

### ISSUE THREAD

**Issue by libertate** [psi-plus/main#767]
При закрытии окна чата конференции по крестику сверху в правом углу происходит выход из конференции и удаление ее из ростера. Такое поведение очень неудобно, так как чаще всего нужно именно свернуть окно конференции, не выходя из нее и не удаляя из контакт-листа. С помощью плагина extended options можно убрать крестик на самой вкладке и настроить сворачивание по двойному клику на ней и клику средней кнопкой мыши. Но крестик на окне KDE никак не убрать, и если по ошибке нажать на него, то все конференции удалятся из списка контактов и придется потом открывать каждую конференцию вручную. Таким образом можно случайно удалить свою комнату, если по ошибке закрыть окно вместо сворачивания. Лучше сделать не закрытие конференций при закрытии окна, а сворачивание, так как сворачивать окна по одному клику на крест удобнее, особенно когда в одном окне открыто несколько вкладок конференций. У меня установлен psi+ из аура [https://aur.archlinux.org/packages/psi-plus-git](url), в окружение KDE 5.16. Дистрибутив manjaro 18.1.0.

![Screenshot_20191004_225848](https://user-images.githubusercontent.com/30025566/66229711-e2565800-e6fb-11e9-8e9f-70c67a67aa68.png)

**Comment by Vitozz** [comment]
Fixed in https://github.com/psi-im/psi/commit/6f5da63c357ee292ef66b61aeff4f16d3db51aa7
