### ISSUE TITLE
Пустое окно CAPTCHA

### ISSUE THREAD

**Issue by 0ktav1us** [psi-plus/main#769]
Приветствую уважаемых разработчиков и всех пси-плюсчиков.
Появилась проблема при входе в конференцию, на этапе ввода каптчи, не показывает цифры для ввода. Прикрепляю скриншот.
Psi+ v1.4.926 (2019-10-23, Psi:951b25c5, Psi+:c58f2bd, webengine)
https://ibb.co/MhPs1XP
http://dpaste.com/188ZPMG

**Comment by Ri0n** [comment]
Xml log расскажет что это за картинка и какой блоб. Если выглядит валидно то возможно не стоит кутишный плагин, который похандлит данный формат картинки

**Comment by 0ktav1us** [comment]
> Xml log расскажет что это за картинка и какой блоб. Если выглядит валидно то возможно не стоит кутишный плагин, который похандлит данный формат картинки

Куда этот xml log пишется ?

**Comment by Ri0n** [comment]
контекстное меню аккаунта -> xml

**Comment by 0ktav1us** [comment]
`<presence to="comp.lang.c@conference.jabber.ru/0ktav1us">
<priority>50</priority>
<c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://psi-plus.com" ver="WDVX3RlaRzq6i02bT0IcgcERXv8="/>
<x xmlns="http://jabber.org/protocol/muc"/>
<x xmlns="vcard-temp:x:update">
<photo>9a33eec86f0d858bf40f79487af3bbcb954b9e7b</photo>
</x>
</presence>

<r xmlns="urn:xmpp:sm:3"/>

<a xmlns="urn:xmpp:sm:3" h="1530"/>

<message id="988508921386278995-416539273465935973416568419345504067170065085267" to="oktavius@jabber.ru/Psi+" from="comp.lang.c@conference.jabber.ru">
<body>Ваши сообщения к comp.lang.c@conference.jabber.ru блокируются. Для снятия блокировки перейдите по ссылке http://captcha.jabber.ru/captcha/988508921386278995-416539273465935973416568419345504067170065085267</body>
<x xmlns="jabber:x:oob">
<url>http://captcha.jabber.ru/captcha/988508921386278995-416539273465935973416568419345504067170065085267</url>
</x>
<captcha xmlns="urn:xmpp:captcha">
<x xmlns="jabber:x:data" type="form">
<field var="FORM_TYPE" type="hidden">
<value>urn:xmpp:captcha</value>
</field>
<field var="from" type="hidden">
<value>comp.lang.c@conference.jabber.ru/0ktav1us</value>
</field>
<field var="challenge" type="hidden">
<value>988508921386278995-416539273465935973416568419345504067170065085267</value>
</field>
<field var="sid" type="hidden">
<value/>
</field>
<field label="Введите увиденный текст" var="ocr">
<required/>
<media xmlns="urn:xmpp:media-element">
<uri type="image/png">cid:sha1+18f3b26a71681bcb13f332b4693d9d01638df16a@bob.xmpp.org</uri>
</media>
</field>
</x>
</captcha>
<data xmlns="urn:xmpp:bob" max-age="0" cid="sha1+18f3b26a71681bcb13f332b4693d9d01638df16a@bob.xmpp.org" type="image/png">iVBORw0KGgoAAAANSUhEUgAAAIwAAAA8CAIAAAFMb/WKAAAGLklEQVR4nO1c25LrOAiUp87//7LPg3cVwqVpkJy4ZpeHqYksCQQIGpyZ4zzPUaefxhq07DiO+VOOoGXHcZznef2cg9fIPxM2nO21mZAHLbvmTc5SBHeLHzuPoc7Zaka7pHWUcRxHpIxLqB87JH9xVarPo9Tokm+oAW3l8Ek1qfUmfYzlg6Z6IrjOvcppbj2gaiXXt98jMasM0k1YTz3P07qVkkPNVyMvTtO5XcHlXnaCEsL1jtBOUl3AFwat2JpHrLhfM8I2iPKI9Fa689UqipO0hyuBCkfXfB177tCea7Nmupab2vjqSu9wqlpFpfNQCDKCpRSFu0koz0TRz84c5mRWMRpD4KQmQ4adiSPWAeINpsj40VYvgMM4goIYLnyKJH7ZyTIDiEUmEVJWH+HIj1j7PKGb67oJmLwtlje8psnpJkpdyU7+TiKkAOD7HLyEN922Iy16C7lJiqJGKQ3iUmeyIctDd1qqFEZr+kguJJG6uaIdEHc+dSuyknBKALz/JKfcsiM2MUSnAoKWlqgzRAjQpcTx3IQNyuwot1ULL1xqFIpvuV5Zw1q/JBAAgIqv+/vIQoIk/y4p0KYAA8B/itxC1S1gI6SnuFC5K3LlNvxDzPjcssDXdzxcPoOfmKIIYX17M8hj9pVFpS0BcIgHj1zMXaU/6nPV4tf8qBRs007HwzF68pPz3XH7kaEtjvd9JL6dfuGR9F36MFU9jUEhqw0py2/Qt2iGFqZynodJJz+oXirtACZvsxIuJVyZ+M0ZuDRpp+MtUiSlRGeMIvYcCWhx0RpyK/LWsUeaGkqzcFQURILiPW3IScvBPeHh8HrVjYCRLinXSwAmM4MXRerHcAkjdDsOBECNXTnYxsURMQaUeF+tAlLld0lW7DjZ42OXorzkVap8RzXiRaq16lTyuTK5OnI7BWO9nSJZMp0G92KkLRfbhLAdjobDoy/7RHmgwSw9JN6zFEX9Qt2udA/WK/JSIysug4slr922YE2lAvxRjazjXUXJF7hSjYK4D1bJcdw2Snew5LQmo9YCZgCyqm39nFmrfrw7dsmSb1XtigNEmYoft4Mq+pGUv6xVpO6ray4ryoQ2h2mSKYkZcIyp2ZqU8tm7Lg+gVoFgbcNMj5x2CpMBGN4WAaQ77ykLQHht7njPKwKeOl9WdQdJd/0A+S82o9vpQortZ1gsZPISEDB2Kxkw0ti2s0ND8Uy2aUi2y+bf/HbKTfQL2/y/8Ei/j778LgYQ2TtZZ2EB5q7W5jAgt5kEHniTovPsjaFgtxVG2Bg9Uz3OSOkhd7l5D0ssbjtadnqckVLaWPpsZFRSffUID3qnObIXLBe5/bHjX9ouDz8t6uOuC3YXcGDagC4xk0FVxsQxMKJqP0a5t6KPi+4y0t7MAbrraVXNyNYuWd0+/zDGTgXAlBsJeFOjBF9BTbJ5a7uhW7i0RZIkW1Gq69+7ZLmRSskTT253hsnIw3BZeSopeu2iPGkYBUbjgPaEO7dwmzLZydvBVWn5RnAI4iQYqSawW76Ep0ThQcSuMMVjB94VZKff5kg7mXxpcp5nKsC9ELzXN55rq315fvmcjLO63ASDiwjXgCU89Y003ySpV0qWzvfX4T12SuklfGy3Av4rz5XaY0DkGY1UqWwk5YPMbZU0QQ6j4urZrCFLy8d7TCOXyxt2h4UG8/eMqpi30stqxgYHl+Ym2FT4qatH98Kld328m2eOuKeI9onkAUxJWoXgpFXSzRmPIzFhtArXVSX5U2l79VBEyVeG1F12w1QqCm+ANNunj5hkY5dYOVMEHwkzg94uCw2+TpqS4SSZEl4iI2dpW95R+IDMPFVy7rXNJGSkKoxxqQfnVJKLckOaM6RhUgdPQZqddodJLBVKOXWGQSeJKIa4SAy4QgTBpSXs+LrMQLzPEBXuomqjx3Ieu3Ev1RzXqd1t0wsdeeHnTWKJMtIu7D/RgfsUhK8ImJEcAVO8yn30+cvE/u2V/HiHiCAMunr5Stj5FlH/nOdWsi0MO+c59viAQizVitld/puWNSlSX5ehRN9NUchIWwKdG6bSKiQ1w4ew7zPgQ6FO6pECxOSeZ/z68gPZ6CG2mfT09JtWP/8FerqR/qcxxl8wzsoCPibjIAAAAABJRU5ErkJggg==</data>
</message>

<iq id="a1131a" to="comp.lang.c@conference.jabber.ru/0ktav1us" type="get">
<data xmlns="urn:xmpp:bob" cid="sha1+18f3b26a71681bcb13f332b4693d9d01638df16a@bob.xmpp.org"/>
</iq>

<r xmlns="urn:xmpp:sm:3"/>

<a xmlns="urn:xmpp:sm:3" h="1531"/>

<iq xml:lang="ru" id="a1131a" to="oktavius@jabber.ru/Psi+" from="comp.lang.c@conference.jabber.ru/0ktav1us" type="error">
<data xmlns="urn:xmpp:bob" cid="sha1+18f3b26a71681bcb13f332b4693d9d01638df16a@bob.xmpp.org"/>
<error code="406" type="modify">
<not-acceptable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Только присутствующим разрешается посылать запросы в конференцию</text>
</error>
</iq>
`

**Comment by 0ktav1us** [comment]
> контекстное меню аккаунта -> xml

капча корректная, qt плагина не хватает судя по всему.

**Comment by Ri0n** [comment]
ах. может быть и нет. ща сверюсь со стандартами

**Comment by Ri0n** [comment]
пофикшено в мастере.

**Comment by Neustradamus** [comment]
When you click on "?", what do you see?

**Comment by Neustradamus** [comment]
@0ktav1us: When you click on "?", what do you see?
