### ISSUE TITLE
athentication error

### ISSUE THREAD

**Issue by pilimotta** [psi-plus/main#773]
Hi, 

I kept getting an athentication error connecting a disroot account. I'm quite sure there are not error in the account. 
A would appreciate any help 
Thanks a lot

**Comment by tehnick** [comment]
What version of Psi+ do you use? In which operation system?

**Comment by pilimotta** [comment]
Hi, Thanks for your answer 
Im on a MacOS catalina (10.15.2) and Psi+ v.1.4.983
And the account that doesn't authenticate is from server disroot.org

**Comment by tehnick** [comment]
> Im on a MacOS catalina (10.15.2) and Psi+ v.1.4.983

Great! Is it basic or webengine version of Psi+?

**Comment by tehnick** [comment]
Also could you try more old version of Psi+?
For example: Psi+-1.4.886-macOS10.12-x86_64.dmg
You may get it here:
https://sourceforge.net/projects/psiplus/files/macOS/tehnick/

**Comment by pilimotta** [comment]
It’s the basic psi+, I’ll try the version you seggested and let you know. Any other advice about the Version already running will be welcome!
Thanks again

**Comment by tehnick** [comment]
> I’ll try the version you seggested and let you know. Any other advice about the Version already running will be welcome!

Just for info: program code related to authorization was not changed between these versions, but build environment was changed significantly. So this test should exclude possible problems in updated version of thirdparty libraries, used by Psi+.

**Comment by pilimotta** [comment]
Hi, 
I've already try the  Psi+-1.4.886-macOS10.12-x86_64.dmg and also Psi+-v-1.4.977-macOS10.15-x86_64.dmg but neither work out. Both has the same problem not authenticating the disroot account.   
:( 
So, any other ideas, please ?

**Comment by Ri0n** [comment]
I tried to check authentication. seems like server problems because Psi sends everything correctly.
I also tried to register an account there but they locked it quickly.

So just ask disroot admins what's wrong with their server.
