### ISSUE TITLE
How to clear history?

### ISSUE THREAD

**Issue by euppi98** [psi-plus/main#775]
Kind, after numerous searches, I could not find the function of cleaning history in the application itself.

**Comment by tehnick** [comment]
History dialog allows you clear history with selected contact.

**Comment by tehnick** [comment]
If you want clear history in a whole in one step, you may do this only from file manager or terminal...

**Comment by euppi98** [comment]
> If you want clear history in a whole in one step, you may do this only from file manager or terminal...

Ok how to do this through a terminal or file manager?

**Comment by Ri0n** [comment]
rm -rf ~/.local/share/psi+/profiles/default/history

Best Regards,
Sergey


пт, 24 янв. 2020 г. в 14:36, Eugene Platonov <notifications@github.com>:

**Comment by Vitozz** [comment]
Should we close this ticket?
