### ISSUE TITLE
this app can't run on your pc

### ISSUE THREAD

**Issue by newmanstuff** [psi-plus/main#783]
I downloaded the version psi-plus-portable-1.4.1471_win7_x86_64 and when about to open I keep getting this message pop up

this app can't run on your pc

**Comment by Ri0n** [comment]
probably your OS architecture is different

**Comment by newmanstuff** [comment]
32 bit .. but this version said :  psi-plus-portable-1.4.1471_win7_x86_64 
it mean support for both 32 and 64

**Comment by Ri0n** [comment]
https://ru.wikipedia.org/wiki/X86-64

**Comment by tehnick** [comment]
https://en.wikipedia.org/wiki/X86-64

**Comment by tehnick** [comment]
@newmanstuff 
Read README on download page please.
