### ISSUE TITLE
Psi+ bug. PLEASE HELP

### ISSUE THREAD

**Issue by Alejandro-M-Rodriguez** [psi-plus/main#792]
Psi+ v0.16.361 doesn't show contacts that i've just added. How to fix it?

**Comment by tehnick** [comment]
This old version of program is not supported by us.

**Comment by Alejandro-M-Rodriguez** [comment]
> This old version of program is not supported by us.

By who this version is supported?

**Comment by tehnick** [comment]
Nobody.
