### ISSUE TITLE
Psi v1.4-dev issue

### ISSUE THREAD

**Issue by Alejandro-M-Rodriguez** [psi-plus/main#793]
Hello, please help: how to increase the height of message fields, shown on screenshot: https://clip2net.com/s/4a5EO7S
Version: Psi v1.4-dev (2018-11-24)

**Comment by tehnick** [comment]
In settings dialog of course.

**Comment by tehnick** [comment]
![Screenshot_20201204_135906](https://user-images.githubusercontent.com/441190/101156055-13505680-3639-11eb-854c-0eb14261205a.png)

**Comment by tehnick** [comment]
Also you may use Extended Options Plugin for more thin customization.

**Comment by Alejandro-M-Rodriguez** [comment]
> Also you may use Extended Options Plugin for more thin customization.

No. I want do chat filed size like a on right window: https://clip2net.com/s/4a5GpR1

**Comment by tehnick** [comment]
> No. I want do chat filed size like a on right window: https://clip2net.com/s/4a5GpR1

See my screenshot above. And do not forget to re-open chat windows or even restart program after changing of this option.

**Comment by Alejandro-M-Rodriguez** [comment]
Thanks, it works. Tell me please how to make upper panel like this https://clip2net.com/s/4a5KR0U

**Comment by tehnick** [comment]
> Tell me please how to make upper panel like this https://clip2net.com/s/4a5KR0U

Enable this toolbox in settings dialog. And configure buttons on it.

**Comment by Alejandro-M-Rodriguez** [comment]
> Enable this toolbox in settings dialog. And configure buttons on it.

Thx. When i do right mouse click on contact in old verison. It shows this panel https://clip2net.com/s/4a662Kk. How to do the same panel in 1.4?

**Comment by tehnick** [comment]
This is not a panel, but a context menu. Nothing changed in it. This context menu is almost the same as earlier.

**Comment by Alejandro-M-Rodriguez** [comment]
If you will compare it you will see, that there are many points in the list are absent 
OLD: https://clip2net.com/s/4a662Kk
NEW: https://clip2net.com/s/4a6CZE0

**Comment by tehnick** [comment]
List exact list of missed items.

**Comment by Alejandro-M-Rodriguez** [comment]
> List exact list of missed items.

On russian language, ok?

**Comment by tehnick** [comment]
It does not matter.
