### ISSUE TITLE
Окно чата попапится на Linux (Fedora) 

### ISSUE THREAD

**Issue by psiplusraiseshit** [psi-plus/main#794]
Уже открытое окно чата попапится при любых событиях: как приходящих сообщениях, так и, когда собеседник просто начинает набирать текст (или перестает)
Никак не отключается. Все возможные пункты в настройках отключил. В Advanced настройках все пункты включающие слова popup, raise, alert выставлены в false. 
Все версии за последние годы имеют такое поведение.
Под Windows и MacOS всё работает корректно. Другие линуксы не пробовал.

**Comment by tehnick** [comment]
Используется Cinnamon?

**Comment by psiplusraiseshit** [comment]
> Используется Cinnamon?

Да

**Comment by tehnick** [comment]
В таком случае мы ничем не можем помочь: https://github.com/psi-plus/main/issues/579
Не используйте Psi+ в Cinnamon. Есть Gajim и другие xmpp клиенты...

**Comment by Vitozz** [comment]
https://psi-plus.com/wiki/ru:faq#%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81_21%D0%BA%D0%B0%D0%BA_%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C_%D1%87%D1%82%D0%BE%D0%B1_%D0%BE%D0%BA%D0%BD%D0%BE_%D0%BD%D0%B5_%D0%B2%D1%8B%D1%81%D0%BA%D0%B0%D0%BA%D0%B8%D0%B2%D0%B0%D0%BB%D0%BE_%D0%BD%D0%B0_%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%BD%D0%B8%D0%B9_%D0%BF%D0%BB%D0%B0%D0%BD_%D0%B2_cinnamon

**Comment by tehnick** [comment]
> Эта настройка доказано работает в Cinnamon 4.2.4 и вероятно в более поздних версиях, хотя в некоторых более ранних версиях она не работала.

Хм, она и правда работает теперь?

**Comment by Vitozz** [comment]
А кто их знает этих разрабов цинамона. Было время, когда они эту настройку вообще убрали. Видимо вой поднялся знатный и они ее вернули. Я даже не удивлюсь, если в текущей версии ее опять убрали

**Comment by artenaki** [comment]
> Предотвращение воровства фокуса, как правило дефолт во всех DE, но Cinnamon - исключение

Не только Cinnamon исключение, но и xfwm4 в Xfce крадет фокус (как минимум в Xubuntu 16.04). И [тестовая утилита](https://github.com/psi-plus/main/issues/579#issuecomment-461403507) это подтвердила. Сам мучаюсь давно с крысой, правда не в Psi. Обычно это проявляется, если запускаю какой-то жирный софт и пока он грузится, начинаю заниматься своими делами, а когда запустится, он крадет фокус. Или в Tixati раз в 1,5 месяца Donate окно на передний план выскакивает. Что интересно, как ни крутил настройки Xfce, становится только хуже. Хотя иногда захват фокуса бывает полезен (то есть предотвращение становится вредным). Например, если открываешь видеофайлы в файловом менеджере, видеоплеер сразу открывается, а не сворачивается, как это бывает в LXDE. Или текстовые файлы. В общем, сложная это тема передача фокуса, и не все так однозначно. Но точно желательно иметь SSD. И когда совсем уж внаглую выскакивает без запроса это плохо. По идее, это должно разруливаться именно приложением.

**Comment by artenaki** [comment]
Если точнее, за управление окнами отвечает не сам Cinnamon (или другая среда), а Window Manager, который при желании можно поменять. Cinnamon использует WM под названием Muffin (что является форком третьегномовского Mutter, который произошел от второгномовского Metacity). Например, в XFCE я устанавливал кдешный WM менеджер KWin со своими настройками предотвращения фокуса и проблема пропадала. В LXDE заменял Openbox на крысиный Xfwm (LXDE даже позволяет менять WM из графического интерфейса). LXQt может использовать много чего: Openbox, Xfwm, Kwin. Так что поменять можно, вплоть даже до подмены бинарника. Визуально от WM зависит только заголовок окон и их контекстные меню.
Вот интересно, перехват фокуса это особенность только Muffin, или он унаследовал это от Mutter? Есть вероятность, что третьегномовцы как обычно поломали все в Mutter (после перехода с GNOME 2), но GNOME 3 вообще среда очень специфичная. Там нет трея, например и переключение окон в отдельном экране. Может быть перехват фокуса предотвращается там каким-то костылем, который не работает в Muffin (Cinnamon).
Поведение фокуса интересная тема, которую нужно изучить. Например, я уже не помню как было в GNOME 2 (Metacity). И ведь еще был Compiz. Могу только сказать, что KDE уже начиная как миниуму с третьей версии позволяет предотвращать потерю фокуса (есть несколько уровней). Openbox как-то непонятно, вроде бы не крадет фокус (и это даже хуже), но у него свои глюки (не запоминает развернутость некоторых окон, маленькие плохокликабельные кнопки). Xfwm4 из XFCE крадет.
