### ISSUE TITLE
Service discovery: Unexpected refresh

### ISSUE THREAD

**Issue by sjehuda** [psi-plus/main#807]
Service discovery refreshes itself unexpected upon change window focus (see second 7 to video) or upon first click (see second 27to video).

[psi_service_discovery-2024-04-26_17.29.47.webm](https://github.com/psi-plus/main/assets/19249089/ba64ed95-a71b-456c-a1f8-3c66570de575)

Reported by @Neustradamus

**Comment by Neustradamus** [comment]
@sjehuda: Thanks for your video!

@Ri0n: When we click on "+" a first time, it is refreshed, and we need to click a second time on "+" to see the details.

Solution is to remove the first refresh to have directly selected details

Linked to:
- https://github.com/psi-im/psi/issues/632
- https://github.com/psi-im/psi/issues/674
- https://github.com/psi-im/psi/issues/707
- https://github.com/psi-im/psi/issues/745
- https://github.com/psi-plus/main/issues/807
- https://github.com/psi-im/psi/issues/791

**Comment by lao-mang** [comment]
несколько раз замечал

**Comment by sjehuda** [comment]
I am curious to know what exactly happens which causes this double refresh in Service Discovery.

I am not coding in C++, yet I sense that knowing about this process might give a good understanding of handling Service Discovery, which I consider an important feature for every XMPP client.

**Comment by Neustradamus** [comment]
I think it has been solved with this commit, thanks to @Ri0n:
- https://github.com/psi-im/psi/commit/5ba075a15b9dfc3b6687295b63b5eb7b18512e80

Psi+ 1.5.1873:
- https://github.com/psi-plus/psi-plus-snapshots/commit/6715a1bed5a042d8bbb6fa0f6ae4edeb154bc6b6

**Comment by sjehuda** [comment]
Service Discovery appears to work as expected.

- No unexpected reload.
- No endless pubsub/nodes within pubsub/nodes.

Shall we close this ticket?

---

Thank you to @Neustradamus for petitioning me several times already to test this issue; I definitely needed that ';-)

**Comment by sjehuda** [comment]
Thank you to @Neustradamus for petitioning me several times already to test this issue; I definitely needed that ';-)
